### ISSUE TITLE
Meta issue: illegal content reporting

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1132]
We have the legal obligation to remove the access to illegal content accessible through Files, as such we need a way for our users to report illegal content and we need a way to remove the access to such content if it is violating our policies.

The flow should look like:
1. "Report content" button available for each file and any user in a shared file.
1. if clicked, we should inform the user that the content will be shared with an admin, technically this means probably downloading the content, decrypting it, sending it to the admin (how?). Also how can you be sure that the content reported is the cid (the file on IPFS is encrypted, hence the cid is different.)
1. a confirmation is sent to the reporting user if we have the email, otherwise a confirmation message is shown
1. an admin can then review the content that was shared. If it violates our policies, the file should be unpinned, we should prevent users from accessing it through our UI, and ban the offending user?

I don't see a way to work around the problem in 2. without strongly lowering our security principles. Any idea @FSM1 or @kalambet ?

**Comment by Tbaut** [comment]
My idea was to actually leverage something that doesn't require too much api/ui work. We certainly need some kind of automation for the admin to remove the pin etc, but going as far as having an admin added to the shared bucket and a UI for this I'm not sure.

**Comment by FSM1** [comment]
For v0, we will just display a message about the user that can be copied and emailed (need a dedicated email for these)

The message should include:
- BucketId
- Full Path
- Encrypted Encryption Key (fetch Admin PubKey from endpoint)

See #1147
