### ISSUE TITLE
Reporting Illegal/Undesirable Content

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1147]
To remain compliant legally, we require a facility to report content that does not comply with the Terms of Service.

See discussions here: https://github.com/ChainSafe/files-ui/issues/1132#issuecomment-862477334

Acceptance Criteria:
- A `Report Content` button in the Options dropdown 
- A modal to display the information necessary to report the content
- Ensure that T&C and Privacy Policy explain that content may be shared with moderators

**Comment by Tbaut** [comment]
@ColinSchwarz as discussed the other day, can you check with our legal team regarding the point 3?
> Ensure that T&C and Privacy Policy explain that content may be shared with moderators

**Comment by Tbaut** [comment]
tackling #1218 first since this will be impacted. Also the sooner the better.

**Comment by Tbaut** [comment]
Circling back on this issue's estimation, this was more a 5/8 than a 3. The amount of external coordination + (optional) refactoring to get the "report modal" as close to the "info modal" as possible made this issue bigger than it seemed.
