### ISSUE TITLE
File Management: User can drag and drop file whilst it is being renamed

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1171]
**Describe the bug**
User can drag and drop a file before the rename changes are saved

**To Reproduce**
1. Login to files
2. Create a folder in your drive root
3. Upload a file to your drive root
4. Start to rename your file but do not save changes
5. Try to move the file to the folder you created

**Observed behavior**
It is possible to drag and drop the file into the folder whilst the file rename components are still being displayed. If you proceed to move it to the folder then the file will be moved with the original name in place. 

After the file has been moved if you navigate to that folder you will see the rename components on that file are still visible. 

**Expected behavior**
It should not be possible to drag and drop the file whilst it is being renamed (or if we want to allow this perhaps we should  prompt the user to save their changes first). 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version : 91

**Additional context**
Happening on dev and current production release

**Comment by Tbaut** [comment]
I'll solve this differently, I'll make any click outside remove the edition (and act like a cancel). The DnD is a pain in the butt and I think this is a fair way to solve the problem.
