### ISSUE TITLE
File Management: User can "move" a file into the folder that it's already in

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1172]
**Describe the bug**
User can "move" a file into the folder that it's already residing in

**To Reproduce**

1. Login to files
2. Create a folder in your drive root
3. Upload a file to your drive root
4. Move the uploaded file into recently created folder
5. Navigate to the new folder
6. Click the kebab menu icon for the file and select move
7. In the folder path selection, select the folder that the file is already residing in
8. Click the move button

**Observed behavior**
A "File moved successfully" toast will appear and the filename of the file will be appended with `(1)`

**Expected behavior**
It should not be possible to move a file into the folder it is already residing in

**Screenshot**
<img width="1296" alt="Screen Shot 2021-06-22 at 10 07 14 AM" src="https://user-images.githubusercontent.com/3982665/122970138-61614900-d342-11eb-95c8-6f9ee53d20e9.png">

**Desktop (please complete the following information):**

OS: macOS
Browser: Chrome
Version : 91

**Additional context**
Happening on dev and current production release

**Comment by Tbaut** [comment]
tbf I think this is not really a problem, nor a bug. Also I don't think is would be easy to change and hide in the tree view. if your current folder contains a folder, you don't want to hide it.

**Comment by Tbaut** [comment]
Based on the UI discussion, we should:
- disable the button when the path selected is the same as the current one
- show a little red text next to the buttons

Maybe @sweetpea22 has a better idea or can sketch out something :)

**Comment by FSM1** [comment]
> Based on the UI discussion, we should:
> 
> * disable the button when the path selected is the same as the current one
> * show a little red text next to the buttons
> 
> Maybe @sweetpea22 has a better idea or can sketch out something :)

I am leaning towards the `disable button` approach, purely from the ease of implementation PoV

**Comment by Tbaut** [comment]
Yup, actually these bullet points are more an "and" than a "or". If you only disable the button without telling why, I think it's not obvious to the users.

**Comment by sweetpea22** [comment]
How about we disable the name of current folder so it can't be selected?

**Comment by Tbaut** [comment]
That was the original suggestion from Andrew, but it's much harder to achieve afaiu.

**Comment by sweetpea22** [comment]
In that case adding a message to a disabled button should work
<img width="843" alt="Capture d’écran 2021-06-29 à 10 16 57" src="https://user-images.githubusercontent.com/47398578/123813731-23749f80-d8c3-11eb-9896-e5d663253fde.png">
