### ISSUE TITLE
File Management: File info gets stuck on loading spinner for a large file 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1174]
**Describe the bug**
User cannot see the file information for a large file

**To Reproduce**

1. Login to files
2. Upload a large file to your drive root (I used a 157mb mp4 file)
3. Click the kebab menu icon for the file and select "info"

**Observed behavior**
The file info modal appears but no other information is displayed, just a loading spinner

**Expected behavior**
It should be possible to view info for all files regardless of file size

**Screenshot**
<img width="1289" alt="Screen Shot 2021-06-22 at 10 24 02 AM" src="https://user-images.githubusercontent.com/3982665/122971970-7c34bd00-d344-11eb-90d7-ae1470819aab.png">

**Desktop (please complete the following information):**

OS: macOS
Browser: Chrome
Version : 91

**Additional context**
Happening on dev and current production release

**Comment by Tbaut** [comment]
This is happening in shared view too, not sure if it's the same error. Getting a 500
```
POST https://stage.imploy.site/api/v1/bucket/e5a9782d-25e5-4385-9570-9da2ee6d4662/file
Object { type: "server", message: "Internal server error" }
```

**Comment by Tbaut** [comment]
@asnaith can you give this one a spin again? I refactored the file info modal and I expect this to have fixed the issue.

**Comment by asnaith** [comment]
@Tbaut Oops I missed this yesterday. I've just re-tested on `dev`. The refactor fixed this issue, I cannot recreate the same issue anymore 🙂
