### ISSUE TITLE
Show available plans in `/plans` page.

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1184]
This component is already implemented `packages/files-ui/src/Components/Modules/Settings/PurchasePlan/index.tsx`

It'll need to be adapted to the new design

![image](https://user-images.githubusercontent.com/12774278/122255306-49b33c00-cece-11eb-8d40-bbfec364ed94.png)

- API to provide a list of all the plans and plan details
- UI to send CC details to Stripe in exchange for a Token
- Token to be provided to API for verification.

More details about the billing flows can be found here:
https://www.notion.so/chainsafe/Design-Meeting-July-19-2021-ab26a38ca9c94ec48eee6d680fffc136
https://drive.google.com/file/d/13ujkxTJSt2HzqR-IPXAdywM4URJSu1yI/view

**Comment by FSM1** [comment]
Closed in #1075
