### ISSUE TITLE
Purchase with card page

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1185]
The list of cards a user has should be retrieved from the API (API endpoint TBD)

The user should be able to choose which card from the list is their default card (Only the default card will be billed)

The user should be able to Add a card - interface needs to be wired up, and once validation has passed, Stripe should be called, to receive a token. This token should then be submitted to the API to enable the card to be added.

**Comment by Tbaut** [comment]
I added the "needs clarification" because I don't know where we should get those element from Stripe, it's be good to add these info
