### ISSUE TITLE
Tests failing because of an unhandled promise rejection in the code

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1199]
Some tests are failing with the `unhandled promise rejection` error. Meaning that something most probably went wrong with the api when uploading a file. This is not logged in the tests

example: https://github.com/ChainSafe/files-ui/pull/1197/checks?check_run_id=2935260060

```
 |   1) File management
 |        desktop
 |          can add/remove multiple files and upload:
 |      Error: The following error originated from your test code, not from Cypress. It was caused by an unhandled promise rejection.
 | 
 |   > Network Error
 | 
 | When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
 |       at createError (http://localhost:3000/__cypress/tests?p=cypress/support/index.ts:29246:15)
 |       at XMLHttpRequest.handleError (http://localhost:3000/__cypress/tests?p=cypress/support/index.ts:28735:14)
```

The screenshots don't help much appart from hinting at a network error on the `/buckets` endpoint
![image](https://user-images.githubusercontent.com/33178835/123778841-d3510980-d8d1-11eb-95e8-bead38fd216a.png)

tbf I don't think there's much we can do here, logging it never the less in case someone has an idea.

**Comment by asnaith** [comment]
@Tbaut I will need to looking into it more but perhaps we could use the cypress intercept command https://docs.cypress.io/api/commands/intercept#Usage. 

Maybe we can set it up to intercept the failure and automatically retry the API request? Although it would be better to know why the API is failing in the first place.

**Comment by Tbaut** [comment]
We can keep this around but I haven't seen this happening in a while. I'd remove this issue from the board for now. I think this was mostly an api problem.

**Comment by asnaith** [comment]
@Tbaut Yeah I agree. I think it was an api an issue that has gone away, I haven't seen it for a while

**Comment by Tbaut** [comment]
closing for now, we can reopen
