### ISSUE TITLE
Set Username - Unable to clear input

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1200]
**Describe the bug**
When a user is setting their Username, it is not possible to delete the last character in the input field.

**To Reproduce**
1. Using an account that has not yet set up a username, log in to the app
2. Navigate to settings
3. Click `Add a username`
4. Enter any value, and then backspace to delete it. The last character will not be cleared.

**Expected behavior**
The field should be cleared

**Console error**
None

https://user-images.githubusercontent.com/12774278/123785348-1b2b5d00-d8e1-11eb-8174-20f93655e361.mp4

**Comment by Tbaut** [comment]
This has been reported and fixed already in staging https://github.com/ChainSafe/files-ui/issues/1170

**Comment by FSM1** [comment]
> This has been reported and fixed already in staging #1170

Ahh nice. I should have merged dev onto my branch before reporting 🙈
