### ISSUE TITLE
New sign-in screen

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/files-ui#1209]
- Input field and primary has been added so people can sign in with their emails faster.
- Web3 button used to be blue, now it's black
<img width="443" alt="Capture d’écran 2021-06-30 à 11 26 17" src="https://user-images.githubusercontent.com/47398578/123988614-28565380-d996-11eb-9dad-876a2012aa82.png">

**Comment by Tbaut** [comment]
Do you have an ethereum logo for me on Figma @sweetpea22 ? I'd add it to the Web3 wallet.
