### ISSUE TITLE
ChainSafe Storage: Upload confirmation dialog not displaying correctly

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1211]
**Description**
The upload modal dialog is not displaying the string correctly and the progress bar does not move during upload

**To Reproduce**
1. Login to ChainSafe storage 
2. Navigate to the Buckets page
3. Create a bucket and click on it
4. Click on the upload button
5. Upload a large file (easier to see if you use a large one that will take a few seconds)

**Expected behavior**
An upload progress modal should be displayed 
 - Informing the user of what is happening 
 - Progress bar should move along with the progress of the upload

**Screenshots**
<img width="476" alt="Screen Shot 2021-06-30 at 12 19 16 PM" src="https://user-images.githubusercontent.com/3982665/124019040-67d46e00-d99d-11eb-9527-9162a18260d6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome version 91.0.4472.114, Firefox version 89.0.2

**Comment by Tbaut** [comment]
I've seen this, however I think this should not happen live, it happens when there's a missing `yarn compile`. I'll check it out.
