### ISSUE TITLE
ChainStorage: Overflow menu obscured in view (2nd level down)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1214]
**Description**
The overflow menu is obscured from view, after navigating into a bucket folder, when you click on the kebab menu icon

**To Reproduce**
1. Login to ChainSafe Storage
2. Navigate to the buckets page
3. Create a new bucket and navigate to it
4. Create a folder and navigate to it
4. Inside the folder upload a file or create a new folder
5. Click on the "kebab" menu icon for the newly created folder / uploaded file

**Expected behavior**
The overflow menu should appear with options

**Screenshots**
<img width="1357" alt="Screen Shot 2021-06-30 at 12 00 29 PM" src="https://user-images.githubusercontent.com/3982665/124023014-5e99d000-d9a2-11eb-9c5c-d4a9215346f8.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 91.0.4472.114 

**Additional context**
We already fixed a very similar issue at the top level in #1192, this is only occurring now at the 2nd level down (within a folder).

**Comment by Tbaut** [comment]
this is a dup of #1189 that has a fix waiting for review.
