### ISSUE TITLE
@chainsafe/files-api-client 404 when yarn installing

### ISSUE THREAD

**Issue by jpangelle** [ChainSafe/files-ui#1230]
**Describe the bug**
I am setting up the repo locally. I've cloned and set up the access key in Github and in my `~/.bash_profile`. Now when I run `yarn install`, I get an error that `@chainsafe/files-api-client` responded with a `404`. In fact, I can not find the repo on Github. Is this a private repo I need access to?

**Console error**
```sh
error An unexpected error occurred: "https://npm.pkg.github.com/download/@chainsafe/files-api-client/1.15.6/519c0840afb6f30b7ec0fd50a172d72b9fdd980a15afcb70c2f0efaf7fb76a97: Request failed \"404 Not Found\"".
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - yarn version: `v1.22.5`
 - node version: `v15.9.0`

**Comment by Tbaut** [comment]
Thanks, this is a very good point, the package for `FilesClientApi` is still behind closed doors on a private Github package. We'll publish it on npm and update you here when done.

**Comment by jpangelle** [comment]
Ok, cool thanks! Just wanted to ensure I was not doing something incorrectly. 👍
