### ISSUE TITLE
New folder in shared folder with writer does not work.

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1234]
**Describe the bug**
New folder in shared folder with writer does not work.

**To Reproduce**
1. Create a shared folder
2. login as a writer to the shared folder
3. Create a new folder
4. API resolves but not folder is created 

**Expected behavior**
New folder should be created.

**Screen recording**

https://user-images.githubusercontent.com/10713353/124507724-3c63e000-ddf0-11eb-8cff-4996d589bfbf.mov

**Desktop (please complete the following information):**
 - OS: any 
 - Browser: any

**Comment by FSM1** [comment]
Great catch Tanmoy. This looks like an API issue to me. I have also tried uploading a file as a writer, and same sort of response. The API responds with a 200, but no files show up.

Sample bucket details:
![image](https://user-images.githubusercontent.com/12774278/124512176-70cfa000-dde0-11eb-9814-4a30be85c064.png)

Request URL: `https://stage.imploy.site/api/v1/bucket/5ddf26a8-8bdb-47dd-988c-6cea954abdcb/mkdir`
Request Body: `{"path":"/heres a test/nested writer mkdir test"}`
Response: 
```
{
  cid: "bafkreifm5bfsrzdnljzx56avka2xeqteuamcnqjsfrbdtwyhcmcwwwbnqm"
  content_type: "application/chainsafe-files-directory"
  created_at: 1625513462
  name: "nested writer mkdir test"
  size: 0
  version: 0
}
```

ls Request: https://stage.imploy.site/api/v1/bucket/5ddf26a8-8bdb-47dd-988c-6cea954abdcb/ls
Request Body: `{path: "/heres a test"}`
Response:`{[]}`

**Comment by kalambet** [comment]
hey @RyRy79261 did you catch it with e2e test?

**Comment by RyRy79261** [comment]
@kalambet for the explorer operations, I didn't add them to my E2E since it was more focused on access testing, I'll add a ticket for some more scenario

**Comment by kalambet** [comment]
Thank you @RyRy79261 , it looks like test was there but the code itself had improper response, I think @dhyaniarun1993 is on it already, please check it with him.

**Comment by Tbaut** [comment]
Likely fixed by https://github.com/ChainSafe/files-api/pull/1251 and probably no UI change needed. Can you check @tanmoyAtb

**Comment by tanmoyAtb** [comment]
Amazing, looks like everything is sorted out! 
No UI change needed!
closing this issue!
