### ISSUE TITLE
ChainSafe Storage: Delete file / folder confirmation dialog not displaying correctly

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1238]
**Description**
The delete file / folder confirmation dialog is not displaying the string correctly

**To Reproduce**
1. Login to ChainSafe storage 
2. Navigate to the Buckets page
3. Create a bucket and click on it
4. Create a new folder
5. Attempt to delete the folder to invoke the delete file / folder confirmation dialog

**Observed behavior**
The string on the delete file / folder confirmation dialog is malformed

**Expected behavior**
The delete file / folder confirmation dialog should display a string informing the user to confirm that they want to proceed with the deletion of file / folder. 

**Screenshots**
<img width="1275" alt="Screen Shot 2021-07-05 at 4 13 47 PM" src="https://user-images.githubusercontent.com/3982665/124523653-d2761700-ddac-11eb-9146-36c568546821.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome version 91.0.4472.114, Firefox version 89.0.2  

**Additional context**
- Seems similar to #1211

**Comment by Tbaut** [comment]
This is the same sort of problem than https://github.com/ChainSafe/files-ui/issues/1211 
I'll check it out
