### ISSUE TITLE
ChainSafe Storage: Handle Async Bucket Deletion Request

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1249]
**Description**
After deleting a bucket it is not removed from the view until you refresh the page or delete another bucket. 

**To Reproduce**
1. Login to ChainSafe storage
2. Create 5 buckets
3. Click the kebab menu for "bucket5" and choose "Delete bucket" 
4. Observe that "bucket5" is still on the page
5. Refresh browser and observe "bucket5" has now been removed from the view
6. Next, delete "bucket4" and without refreshing the page delete "bucket3"
7. Observe that after deleting "bucket3" that "bucket4" is removed from the view but "bucket3" remains

**Expected behavior**
The deleted bucket should be removed from the view instantly after deletion action 

*(or if there's queuing for the deletion then we should provide the user with information letting them know the attempt was successful and it's now being queued for deletion). 

**Console error**
Appears in the console after deletion attempt: 
<img width="416" alt="Screen Shot 2021-07-07 at 9 58 51 AM" src="https://user-images.githubusercontent.com/3982665/124800183-3530f500-df0a-11eb-9aaa-b37289b2bb08.png">

**Video**
https://user-images.githubusercontent.com/3982665/124799178-1ed66980-df09-11eb-94d2-faec9a9218a7.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by RyRy79261** [comment]
@asnaith So I just ran on my machine and the menu doesn't have delete so I'm guessing that functionality isnt available at the moment

**Comment by asnaith** [comment]
@RyRy79261 Uhm I'm confused but I guess there's still some other things in flux at the moment. It was there last week but now I can no longer create or delete buckets on https://storage-ui-stage.onrender.com.

**Comment by asnaith** [comment]
@RyRy79261 I've logged what we are seeing today as a separate issue because there are errors in the console (https://github.com/ChainSafe/files-ui/issues/1261). 

When that's resolved it should be clearer to see what's happening in this issue.

**Comment by asnaith** [comment]
@RyRy79261 The "Delete bucket" menu option is back now and the issue described originally can still be reproduced.

**Comment by RyRy79261** [comment]
Ohhhhhhh I thought this was share buckets 🤦🏻 

So if I'm correct, deleting buckets is a sort of queued action on the api that happens async, which can still be happening after the api returns a response

@dhyaniarun1993 you think this is something for me to investigate or is deleting buckets still underway?

**Comment by RyRy79261** [comment]
@FSM1 So I dont think its triggering a fetch after the delete finishes 

Also after creating my first bucket, this ghost one popped up that I cant delete that has data in it already
![image](https://user-images.githubusercontent.com/10461622/125643539-2d6b783f-bb5e-47b3-b1ee-0d6e9224f823.png)

**Comment by FSM1** [comment]
> @FSM1 So I dont think its triggering a fetch after the delete finishes
> 
> Also after creating my first bucket, this ghost one popped up that I cant delete that has data in it already
> ![image](https://user-images.githubusercontent.com/10461622/125643539-2d6b783f-bb5e-47b3-b1ee-0d6e9224f823.png)

Should just be a simple `refreshBuckets` call that needs to be added in.

**Comment by FSM1** [comment]
The API call to delete a bucket only queues the deletion up. The API team will expose a status flag that we can use to drive the UI and show buckets that are being deleted currently in a different manner (greyed out, or something similar).

This will depend on API providing the status to the UI.

**Comment by RyRy79261** [comment]
@asnaith @FSM1 

Got a PR up on API for the flags
https://github.com/ChainSafe/files-api/pull/1308
