### ISSUE TITLE
ChainSafe Storage: Bucket browser does not display "Date uploaded" data

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1250]
**Description**
The "date uploaded" data is not being displayed on the bucket browser component 

**Steps to Reproduce**
1. Login to ChainSafe storage
2. Create a bucket
3. Navigate to the newly created bucket 
4. Upload a file

**Observed behavior**
There is no date shown in the "Date uploaded" column 

**Expected behavior**
The date should be displayed in the "Date uploaded" column

**Screenshots**
<img width="1067" alt="Screen Shot 2021-07-07 at 3 56 19 PM" src="https://user-images.githubusercontent.com/3982665/124838541-eac86c00-df3b-11eb-9b03-165f657c0a47.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by FSM1** [comment]
Double checked and the API is returning a `0` for the createdAt property of a just-uploaded file
![image](https://user-images.githubusercontent.com/12774278/126509112-ff8c1249-6a46-4e8d-ac4f-a6be40b65c86.png)

**Comment by FSM1** [comment]
Superceded by #1354
