### ISSUE TITLE
ChainSafe Storage: No character limit enforced on bucket name

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1272]
**Describe the bug**
Currently we are not restricting the amount of characters that can be entered for a bucket name

**Steps to Reproduce**
1. Login to Storage
2. Navigate to the buckets page
3. Click the "Create Bucket" button
4. Enter a ridiculously large string for the bucket name
6. Click the "Create Bucket" button

**Observed behavior**
The bucket with huge name will be created and whilst the bucket browser handles this well (it just truncates the string) when you navigate inside the bucket it will try and display the large name and cause a horizontal scroll bar to appear. This can cause the name to overlap over the side navigation bar. 

**Expected behavior**
It would be best to enforce a limit on the amount of characters that can be entered to prevent other weird display (and perhaps even API) issues that might arise from using a huge string as the name. 

**Screenshots**
Bucket Browser view
<img width="1287" alt="Screen Shot 2021-07-14 at 2 30 07 PM" src="https://user-images.githubusercontent.com/3982665/125696544-78c7e1d3-8322-4219-80af-57b4d1f88ff1.png">

Inside bucket view
<img width="2527" alt="Screen Shot 2021-07-14 at 2 29 25 PM" src="https://user-images.githubusercontent.com/3982665/125696556-31a5843a-21c1-4ac1-8543-71527d3bf352.png">

**Desktop**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by FSM1** [comment]
Closed in #1302
