### ISSUE TITLE
ChainSafe Storage: Folder can be moved into it's subfolder

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1276]
**Description**
It's possible to lose complete access to a folder (at least in the UI) by moving a folder to a subfolder within itself 

**Steps to Reproduce**
1. Login to Storage
2. Create bucket
3. Navigate to newly created bucket 
4. Create a "Folder1" in the bucket
5. Navigate inside "Folder1" and create another folder inside it called "Folder2" 
6. Return to the main bucket view and select "Folder1"
7. Click the "Move selected" button 
8. In the move modal, expand Folder1 so that Folder2 can be selected
9. Select "Folder2" as the destination and click "Move"

**Observed behavior**
It's possible to move a folder into it's subfolder and then lose complete access to both folders in the UI

**Expected behavior**
It should not be possible to move the folder into a subfolder within itself 

**Screenshots**
<img width="875" alt="Screen Shot 2021-07-14 at 3 18 28 PM" src="https://user-images.githubusercontent.com/3982665/125700564-f61e2ee0-19ab-4f3b-b6cf-9ee7e6dbefdd.png">

**Video**
https://user-images.githubusercontent.com/3982665/125700569-672a2758-66c7-4dfd-8e81-76cc61fa979b.mov

**Desktop**
 - OS: macOS
 - Browser: Firefox
 - Version : 89.02

**Comment by Tbaut** [comment]
That's a pretty critical one that affects Files and Storage. Taking a look
