### ISSUE TITLE
Breadcrumb for shared folders should start at the overview 

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1284]
Edit: look at the [last post](https://github.com/ChainSafe/ui-monorepo/issues/1284#issuecomment-1087777710) in this conversation, this is what we want to have.

---
I find it difficult to know whether I'm in a shared folder or if I'm in my home. Ping @sweetpea22 
I'd like to suggest some changes:

- different colors for the root shared folder
- different color for the breadcrumb to know right away?
- the shared folder at the root instead of the home

![image](https://user-images.githubusercontent.com/33178835/125856901-3bb5d1b0-1e9a-4cbe-a403-6e20bffaaee4.png)
![image](https://user-images.githubusercontent.com/33178835/125857927-c37ca6f5-ef30-48e3-a22b-2f9f9f04fcfe.png)

**Comment by sweetpea22** [comment]
Hey, great thinking. Having the folders change to blue for sharing is an excellent idea. With breadcrumbs...I'm toying with the idea of changing the root folder icon to something more clearly clickable, for now I think your idea of having it replace the home icon is awesome. Let's fly with that? And if it's still not enough we'll change the color of the breadcrumb too

**Comment by Tbaut** [comment]
Another one that would make it easier to know, clearly show in the nav bar where we are. Either with some blue, or the font change?

**Comment by sweetpea22** [comment]
Heh, you're ahead of the curve always :P these are the changes to sidebar once the new UI comps are added: 

hover:
<img width="280" alt="Screen Shot 2021-07-16 at 8 14 53 AM" src="https://user-images.githubusercontent.com/47398578/125945827-f6290f23-64e8-412d-81d4-b97c6888b151.png">

active:
<img width="392" alt="Screen Shot 2021-07-16 at 8 14 57 AM" src="https://user-images.githubusercontent.com/47398578/125945824-be1b21b6-276c-478d-9d1a-08414b8c516f.png">

what do you think?

**Comment by Tbaut** [comment]
I'm all for it :raised_hands:

**Comment by serenaho** [comment]
Question: In regards to the solution mentioned above (changing folder colors), are we showing shared folders within the Home page too? If not, there may not be a need to do so.

A way to keep things consistent would be to add the shared icon (see examples below):
1. Above the main header in the Shared Folders page
2. To the breadcrumb whenever a user clicks into a folder

The icon and breadcrumb addition will help users know where they are within the Files UI

> <img width="228" alt="Screen Shot 2022-03-23 at 1 48 22 PM" src="https://user-images.githubusercontent.com/91699405/159793210-4916a0b0-e033-4d32-90f3-146dc8b9f950.png">

> <img width="280" alt="Screen Shot 2022-03-23 at 1 48 27 PM" src="https://user-images.githubusercontent.com/91699405/159793213-a83fa968-a116-436b-a8a6-9f5470e598f6.png">


Ideally, we should also change the navigation icon for Home to be the same house as in My Files like so:

<img width="137" alt="Screen Shot 2022-03-23 at 1 48 51 PM" src="https://user-images.githubusercontent.com/91699405/159793218-ccff88b1-8ec3-4964-9e94-74ef8bcb2422.png">

**Comment by asnaith** [comment]
> Question: In regards to the solution mentioned above (changing folder colors), are we showing shared folders within the Home page too?

@serenaho nope they don't show on the home page, shared folders can only be seen on the `/shared-overview` page and accessed from there. 

An icon difference in the breadcrumb sounds like a good improvement for sure :)

**Comment by Tbaut** [comment]
Agreed that changing the icon would help already. Although to me, back to the origin of this issue
> I find it difficult to know whether I'm in a shared folder or if I'm in my home.

I feel that just a breadcrumb icon change would not be enough. The active menu being blue should also help a lot like so 
![image](https://user-images.githubusercontent.com/33178835/159887573-45b1c3b6-5bdb-416c-b7a7-232587f9943d.png)

Another thought and annoyance that I had while navigating, is that clicking the home/shared breadcrumb button brings you back to the root of the shared folder you're in, not to the shared folder overview. Not sure if that's just me, but I found that somewhat annoying as I expected to be back at the highest level of the tree, the shared folder overview, and not at the highest level of this shared folder. If we do change the breadcrumb icon to look like the shared icon, then we also need to make sure clicking it bring back to the folder overview. lmk your thoughts.

**Comment by serenaho** [comment]
I agree that the icon should lead back to the shared folder overview (sorry I wasn't very clear in my post). I think ideally the breadcrumb would be as follows:

i.e. **Icon** / **Folder X**
Icon = Overview page
Folder X = Root of shared folder

Also agree that there should be an active state for navigation items. I like the addition of the blue, but perhaps we could introduce it in more of a subtle way by just changing the font color:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/91699405/159978887-61264d5f-4e0c-4725-b612-faee3a27b441.png">

**Comment by asnaith** [comment]
> Agreed that changing the icon would help already. Although to me, back to the origin of this issue
> 
> > I find it difficult to know whether I'm in a shared folder or if I'm in my home.
> 
> I feel that just a breadcrumb icon change would not be enough. The active menu being blue should also help a lot 

I agree, the breadcrumb change plus a blue active menu would be great. 

> Another thought and annoyance that I had while navigating, is that clicking the home/shared breadcrumb button brings you back to the root of the shared folder you're in, not to the shared folder overview. Not sure if that's just me, but I found that somewhat annoying as I expected to be back at the highest level of the tree, the shared folder overview, and not at the highest level of this shared folder. If we do change the breadcrumb icon to look like the shared icon, then we also need to make sure clicking it bring back to the folder overview. lmk your thoughts.

👍 Yeah, agree with this too. I think that seems more logical.

**Comment by asnaith** [comment]
@Tbaut regarding the active menu highlighting - were you thinking of doing that for the mobile slide-out menu too? It's not always visible but maybe it could still be useful for the user to know where they are currently at when they slide it out to navigate elsewhere?

**Comment by Tbaut** [comment]
@serenaho 
> i.e. Icon / Folder X
Icon = Overview page
Folder X = Root of shared folder

The root of the shared folder has no name though. Did you mean that we should name it with the name of the shared folder? I'm not too sure how that's end up look like, because those names are prob quite long and descriptive, meaning we'd hide part of it.

We could also name it "root" but I feel that it's too techy and would confuse users. I've a hard time coming up with a good idea there...

**Comment by tanmoyAtb** [comment]
> @serenaho
> 
> > i.e. Icon / Folder X
> > Icon = Overview page
> > Folder X = Root of shared folder
> 
> The root of the shared folder has no name though. Did you mean that we should name it with the name of the shared folder? I'm not too sure how that's end up look like, because those names are prob quite long and descriptive, meaning we'd hide part of it.
> 
> We could also name it "root" but I feel that it's too techy and would confuse users. I've a hard time coming up with a good idea there...

How about this for the breadcrumb 
"Home/Shared users ICON" (for shared-overview) / "Shared folder name" (This is root of shared folder) / "Folder name" / "Folder name" / ...
Even if the shared folder name itself may be long/descriptive, that really should make the most use to the user IMO

**Comment by Tbaut** [comment]
I'm not sure I understand what you mean with "Home/Shared users ICON" (for shared-overview)"

I agree that the shared folder title as the root would work well.

**Comment by serenaho** [comment]
> I'm not sure I understand what you mean with "Home/Shared users ICON" (for shared-overview)"

^ @tanmoyAtb I'm also not sure I understand this because you don't have to access the Home page in order to access the Shared Folders Overview page, so starting with the Shared Folder Overview page (the icon) might be more intuitive.

As for the problem with the Folder name being too long, I think it should be okay since the breadcrumb text size is quite small. As an option though, we could set a maximum length for the breadcrumb and start adding ellipses when the length is reached (except for last folder name)? Like below:

**Current:**
👥 / Shared Folder Title / Folder Title / Folder Title / **Folder Title** 

**Suggested:**
👥 / Shared ... / Folder ... / Folder ... / **Folder Title**

(👥 = Shared Overview)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1284?planning-poker) with ZenHub @tanmoyAtb @Tbaut
