### ISSUE TITLE
ChainSafe Storage: Delete confirmation modal displays the wrong text

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1296]
**Description**
When deleting a folder, the delete confirmation modal refers to a "file" instead of "folder" in the string

**Steps to Reproduce**
1. Login 
2. Create a folder
3. Attempt to delete the folder

**Observed behavior**
The delete confirmation modal contains the string "You are about to delete 1 file" 

**Expected behavior**
The delete confirmation modal should contain the string "You are about to delete 1 folder" 

**Screenshots**
<img width="1048" alt="Screen Shot 2021-07-19 at 10 50 16 AM" src="https://user-images.githubusercontent.com/3982665/126213201-e0e41c88-901d-46e0-bc3e-4edb57da44b1.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by RyRy79261** [comment]
@asnaith @FSM1 @sweetpea22 

So the issue here is that, while for the case of 1 item I could work out if its a file or folder, it gets unclear when deleting a mix, I can add logic to work that out but we could replace file with item

This issue should also be present in Files too

**Comment by FSM1** [comment]
> So the issue here is that, while for the case of 1 item I could work out if its a file or folder, it gets unclear when deleting a mix, I can add logic to work that out but we could replace file with item
> 
> This issue should also be present in Files too

Yeah I have also been thinking about this. My gut feel is to keep it simple and just call it an `item`.

Definitely apply the same changes to `Files` if the error is present there as well.

**Comment by asnaith** [comment]
@RyRy79261 👍 "Item" seems like a good choice to me too
