### ISSUE TITLE
ChainSafe Storage: No error / info when creating a bucket with the same name as an existing bucket

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1297]
**Description**
There is no feedback given to the user when attempting to create a bucket with the same name as a pre-existing bucket. 
Upon clicking "Create" the dialog closes but nothing happens because the bucket is already there. 

**Steps To Reproduce**
1. Navigate to the buckets page
2. Create a new bucket with a unique  #name
3. Create another bucket using the same name that was used previously 

**Expected behavior**
Inform the user on the modal that a bucket with the same name already exists

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by FSM1** [comment]
Since bucket names are only used for display purposes there is no reason for multiple buckets not to use the same display name.

**Comment by asnaith** [comment]
@FSM1 Thanks for the clarification Mike, I've updated the title and expected behaviour to align with this.

**Comment by asnaith** [comment]
Updated again 😄. 

Quick note for anyone following this - A duplicate bucket name does throw an error at the api level so we will add a validation rule that the bucket name must be unique based on the current list of buckets the user has.
