### ISSUE TITLE
Add paging to CIDs page

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1325]
Add pagination to the CIDs page,
The lists API already has support for limits, need to check if there's support for page number.

We need an API endpoint that will return the total number of PinStatus objects that the user has created, and this would drive the logic of whether there are additional pages or not.

**Comment by sweetpea22** [comment]
![Frame 210](https://user-images.githubusercontent.com/47398578/134736194-bb7053de-385c-422f-8bac-b6b6e3f89a5f.png)

We can use the same paging functionality as the one used in Eth2 Crawler @tanmoyAtb

**Comment by tanmoyAtb** [comment]
> ![Frame 210](https://user-images.githubusercontent.com/47398578/134736194-bb7053de-385c-422f-8bac-b6b6e3f89a5f.png)
> 
> We can use the same paging functionality as the one used in Eth2 Crawler @tanmoyAtb

Oh yess ! It would great to have the paging component in the common-components !
