### ISSUE TITLE
Add Rename option to Kebab menu for files in a bucket

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1330]
**Description**
Options missing from Kebab menu - Rename 

**Steps to Reproduce**
1. Login to ChainSafe storage
2. Create a bucket
3. Upload items to bucket
4. Click on the kebab menu for one of the items

**Observed behavior**
Only Move, Delete options are available

**Expected behavior**
The Rename option should be avilable in the menu. Validation of the desired name should be added to ensure that only valid names are submitted.

The edit mode should be mobile responsive (Modal dialog with buttons instead of inline editing)

**Screenshot**
<img width="201" alt="Screen Shot 2021-07-23 at 1 34 48 PM" src="https://user-images.githubusercontent.com/3982665/126838615-c3112c58-3f09-458a-8d2d-af71fdd63cc1.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by RyRy79261** [comment]
@FSM1 @kalambet  I'm not sure where the current options came from, I can got ahead n update just wanna confirm

**Comment by FSM1** [comment]
Im still not sure we want to allow any additional options for storage to be honest. S3 doesn't...

**Comment by asnaith** [comment]
Perhaps the only applicable option that is missing is "rename" then?
