### ISSUE TITLE
Both an error and a success message displayed after sharing

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1336]
Reported by @sadiq1971 

You end up with an error and a success message.
Would you mind adding any more info you have?

![image](https://user-images.githubusercontent.com/33178835/126960916-ae369d82-58aa-4b80-9afb-2f48fb901360.png)

**Comment by sadiq1971** [comment]
@Tbaut, It's easy to re-generate this.
Try to share a large file and disconnect your internet.
I think File Added Successfully is shown by not checking the error.

**Comment by Tbaut** [comment]
yup, thanks for the additional info, I fixed it in #1364
