### ISSUE TITLE
Files: No option to delete a shared folder after it's creation 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1344]
**Description**
There is no ability to delete a shared folder once it has been created 

**Steps to Reproduce**
1. Login to Files
2. Create a shared folder
3. Attempt to delete a shared folder

**Expected behavior**
An owner of a shared folder should be able to delete it once it has been created

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by FSM1** [comment]
This is being handled in #1303
