### ISSUE TITLE
Change the edit icon for shared folder permission edition

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1349]
This is a refresh/reload icon, and it doesn't convey the idea of permission edition. Can we think of something better? ping @sweetpea22
![image](https://user-images.githubusercontent.com/33178835/127133174-bfa966f1-b1e7-4f6d-859e-47487f60a19e.png)

**Comment by RyRy79261** [comment]
Maybe one of those document edit icons, document shape with tiny pencil

**Comment by sweetpea22** [comment]
<img width="403" alt="Screen Shot 2021-07-27 at 7 22 12 AM" src="https://user-images.githubusercontent.com/47398578/127145653-e8d1964e-18bc-40a6-a2aa-063a0650c8ba.png">
What about if we used a user group icon?

**Comment by Tbaut** [comment]
Awww yes, the new name + the icon make total sense to me.
