### ISSUE TITLE
File cannot be recovered from the Bin

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1359]
**Description**
Once a file has been deleted it cannot be recovered from the bin

- If the user has no folders then it's not possible to select "Home"
- If the user has folders in their "home" when the user tries to select one they will get a message to say the "files are already in this folder" although they are not

**Steps to Reproduce**
1. Login to Files
2. Upload a file
3. Delete a file
4. Attempt recovery of file from the Bin

**Expected behavior**
The user should be able to successfully recover the file from their bin to either the home root directory or a specific folder within it. 

**Videos**

https://user-images.githubusercontent.com/3982665/127198387-fdff40e9-f10f-431d-b859-fd0f6c87b226.mov

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 91.0.4472.114

**Comment by Tbaut** [comment]
Thanks Andrew, this is such a basic thing, we need a test for that.
