### ISSUE TITLE
Add some slides to explain our sharing strategy

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1361]
The way we do sharing is different than how users may be used to. For this reason, we should show a little explanation about how sharing with Files works:
- it should show on click on "shared" in the nav bar, or when sharing a file for the first time
- it should be skipable
- it should tell about creating a shared folder
- it should tell about how to create a nickname in the settings
- the more pictures/gifs the better

**Comment by Tbaut** [comment]
We got a consensus on the following. I'll start the work without the pictures from @sweetpea22 for now

• You can now create Shared Folders to share your files (picture of a folder with several users around it)
• Add readers or writers by nickname, sharing id or ethereum address (picture of a user with an ethereum logo, and a well known nickname like Alice or Bob or devops199 for fun maybe?)
• Create your own public nickname in the settings and start sharing! (not sure about the picture here)

**Comment by sweetpea22** [comment]
hey, forgot to add the pics to the issue: 
<img width="1065" alt="Screen Shot 2021-08-25 at 9 21 44 AM" src="https://user-images.githubusercontent.com/47398578/130798213-5e999d42-3e50-4082-b0f7-0efd19887ee5.png">
<img width="817" alt="Screen Shot 2021-08-25 at 9 23 15 AM" src="https://user-images.githubusercontent.com/47398578/130798424-3ebb8a4c-1745-4d28-9faa-439fd531d13c.png">

<img width="823" alt="Screen Shot 2021-08-25 at 9 21 53 AM" src="https://user-images.githubusercontent.com/47398578/130798253-ccbae12b-d247-498a-b7ea-de26de265232.png">

**Comment by Tbaut** [comment]
This is great!! thanks Cindy!
