### ISSUE TITLE
User should be able to add a card to their account

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1368]
A user should be able to add a card to their account.

The card details should be sent to Stripe API directly, and the token received from Stripe should be submitted to the API

**Comment by sweetpea22** [comment]
<img width="839" alt="Screen Shot 2021-08-03 at 11 34 28 AM" src="https://user-images.githubusercontent.com/47398578/128043897-250b66b3-b99b-49cd-9d5b-0c033ca66b75.png">

So i've redone the billing section of settings, i'm thinking it might be better to have one card on file at a time, and the user can update it (add a new card to the account). That way we don't need to track the defaults. What do we think?

**Comment by sweetpea22** [comment]
<img width="1091" alt="Screen Shot 2021-08-03 at 12 12 26 PM" src="https://user-images.githubusercontent.com/47398578/128049771-267f8a36-45c9-4781-b404-9e40ec7e76d8.png">

^ has the same info as stripe, please lmk if i'm missing stuff

**Comment by tanmoyAtb** [comment]
> <img alt="Screen Shot 2021-08-03 at 12 12 26 PM" width="1091" src="https://user-images.githubusercontent.com/47398578/128049771-267f8a36-45c9-4781-b404-9e40ec7e76d8.png">
> 
> ^ has the same info as stripe, please lmk if i'm missing stuff

afaik, wee don't need country or zip code to actually add a card, we can skip them if we want.

**Comment by tanmoyAtb** [comment]
> <img alt="Screen Shot 2021-08-03 at 11 34 28 AM" width="839" src="https://user-images.githubusercontent.com/47398578/128043897-250b66b3-b99b-49cd-9d5b-0c033ca66b75.png">
> 
> So i've redone the billing section of settings, i'm thinking it might be better to have one card on file at a time, and the user can update it (add a new card to the account). That way we don't need to track the defaults. What do we think?

Looks amazing. 
quick question, what happens if you hit Update card, does that open add new card modal, 
and if its the default card, not sure if removing that card should be an option!

**Comment by Tbaut** [comment]
Removing a card should always be an option IMHO, sure it'll cancel the subscription if no new one is added, but that should still be possible.
