### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by comradekingu** [ChainSafe/files-ui#1370]
What does
>All files-ui code are licensed under the GNU Lesser General Public License v3.0 also included in our repository in the LICENSE.md file

mean, and where is the actual source code?

**Comment by Tbaut** [comment]
Thanks for opening this issue. `files-ui` was the name of this repo until very recently. It is now called ui-monorepo. I just submitted a PR to correct this. To answer your question, the actual source code under this licence is all the code in this ui-monorepo repo :)
