### ISSUE TITLE
Elements displayed over each other when vertical height of browser reduced

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1372]
**Description**
I noticed that some elements will start to be displayed over other elements when the vertical height of the browser is reduced. 

I'm not completely sure what can be done about this or what the expected outcome is for this type of scaling down. I've seen some websites lock or reposition elements until it gets to a certain boundary and then afterwards the element just gets hidden if the browser window is reduced even further. 

The chance of a real user using the site at such a reduced height seems low though and don't think this is an issue with much impact so feel free to close if there's nothing to do here but just wanted to share my observations. 

**Videos**

"Getting started" screen

https://user-images.githubusercontent.com/3982665/127404505-767121db-5561-415f-a37b-9fb0750f9d95.mov

Main Navigation bar

https://user-images.githubusercontent.com/3982665/127404149-aa64897d-3ec9-46a5-972b-00ffb44aff7c.mov

**Comment by Tbaut** [comment]
Yeah I personally see this all the time because we have the dev tool open and this eats half of the screen. I don't think it's an issue indeed.
This absolute positioning is less than ideal though and a scrollbar would be better. Let's keep that in mind and avoid absolute positioning as much as we can.

**Comment by Tbaut** [comment]
Closing as we won't address this unless there are some valid complains
