### ISSUE TITLE
Resolve issues with local session being cleared after calling cy.reload

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1381]
**Task:**
Investigate why the local session is being cleared after `cy.reload` is called. 

**Acceptance Criteria**

- Figure out why the local session is being cleared after calling `cy.reload` (or if we have no luck resolving the problem then replace the use of it all together). It wasn't doing this originally though and we had been using that command with no issues in the past so not sure if it's 100% a cypress-only issue. 

- Remove the work around in `commands.ts` that's currently in place after `cy.reload`

**Comment by Tbaut** [comment]
Removing the cy.reload altogether sounds like a good idea, I think we added it because sometimes the UI was quicker than our script and we didn't login correctly because the data wasn't picked up in the local storage. But this was certainly not the best thing to do.

**Comment by Tbaut** [comment]
no more `cy.reload` since #1421, hopefully no more problem.
