### ISSUE TITLE
File recovery not possible without pre-existing folders in home

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1382]
**Description**

A follow on from the work done in #1365. 

If no folders exist in the home directory then it's not possible to choose the home folder itself to recover a file. If you have at least one folder in home then there is no issues recovering a file.  

**To Reproduce**
1. Login to files
2. Remove all files and folders in home directory 
3. Attempt to recover a file from the bin

**Expected behavior**
User should be able to recover a file regardless of wether they have a folder in the home directory or not. 

**Screenshots**
<img width="610" alt="Screen Shot 2021-07-29 at 10 20 41 PM" src="https://user-images.githubusercontent.com/3982665/127604468-a9cbf573-365d-457f-8398-60ce30c51e2d.png">

**Comment by asnaith** [comment]
@Tbaut I must have only tested your changes in #1365 when I had a folder already in my home directory so I didn't see this issue during review 🤦‍♂️

**Comment by Tbaut** [comment]
Ah nice catch, I suspect it's yet another problem related to path, because I worked mostly on the validation part, whereas this seems to be a problem with the display of the current tree with the edge-case when the tree is empty.
