### ISSUE TITLE
Expose the decryption key in the file info (hidden by default)

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1392]
The bucket decryption key is only printed in the console.
As a transparency feature, we should have it displayed in the file info, prob. hidden by default, and let users show it with a click on an eye icon, a little like it's done for the keys on Storage.

The decryption key will be the same for each file in a given bucket/shared folder but I think it's where it's needed rather than putting it in a setting tab with a table for all the shared folder :man_shrugging:

**Comment by FSM1** [comment]
Agreed that showing it on the file-info dialog would probably make the most sense.
