### ISSUE TITLE
Test the folder name validation upon testing the folder creation

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1409]
Consequently to https://github.com/ChainSafe/ui-monorepo/pull/1383#pullrequestreview-722504018

We should make sure that the button is disabled and that there's an error when we try to create a folder with a / in the name, or only white spaces.

**Comment by asnaith** [comment]
Hey @Tbaut, the "Create Folder" modal is not working as described above.

- The user has to click "Create" before the error is shown on the modal
- The "Create" button is not disabled when the error message is shown
- The error displayed when white space only is entered is "Please enter a name" (which could be more informative)

I've created a draft with folder name validation tests, aligned with the current way it is working, but not sure if we want to update the behaviour in the app to match what you described?

**Comment by Tbaut** [comment]
Yup good point, the implementation needed some love to be consistent with the rest. Regarding the error message, I think it's not a big deal to ask for a name when the user have entered a space :man_shrugging: 

I'm generally reluctant to test exactly the chain of character of the error, preferring making sure: some error are visible, so that the test doesn't break if we ever change our mind, but I left your check untouched just because they where here.

**Comment by asnaith** [comment]
@Tbaut Ok. Let's leave the checks as they are for now but if we change strings often (probably unlikely for validation errors) and the tests become a maintenance chore we'll just change it to check the visibility of the element but not it's actual text value.
