### ISSUE TITLE
Allow for downloading files from a bucket

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1418]
**Is your feature request related to a problem? Please describe.**
It should be possible for a user to download a file that has been uploaded to a bucket

**Describe the solution you'd like**
The File item context menu should have a download option, which will download the file using the browser's native downloader

**Additional context**
This should replicate the Files download functionality, except that there is no need for decryption, nor handling the download in JS land. Just direct the browser to the content on the IPFS gateway, and let it handle the download.

**Comment by Tbaut** [comment]
If there's no decryption, can't it then be a direct download from an IPFS gateway? No need for download progression then.

**Comment by FSM1** [comment]
I guess we could just let the browser handle this, though for consistency sake, handling the download in JS land is quite easy to do...

**Comment by Tbaut** [comment]
I'm the first to like consistency (at least for one product), but I think for this one there's no need to make it more complicated. I'm pretty sure a browser handles that better than we'd do. Leave the page and it's canceled, no speed indication. I'd keep it simple :)

**Comment by FSM1** [comment]
Updated the original issue description 🌮

**Comment by RyRy79261** [comment]
https://www.samanthaming.com/tidbits/38-html-download-attribute/

Using html elements for this wont work

**Comment by RyRy79261** [comment]
Cors error when downloading blob manually with Axios:
https://ipfs.chainsafe.io/ipfs/QmX9WfA5UCtp8voUQC8ctDNRJ6MWPZothuRUFKJhGeoteY
![image](https://user-images.githubusercontent.com/10461622/128555748-cd5df516-2e22-4b04-99b9-7719cecadd00.png)

**Comment by Tbaut** [comment]
oooh thank you so much for checking it out, so it's just not possible because of CORS right?
