### ISSUE TITLE
Allow for copying the CID

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1431]
**Describe the bug**
CID text can currently not be selected

**To Reproduce**
1. Log in to Storage
2. Navigate inside a bucket with some files uploaded to it.
3. It is not possible to manually select the CID text

**Expected behavior**
A button for the user to easily copy the CID to the clipboard for further use.

**Comment by Tbaut** [comment]
edit: the original issue was edited, comment not relevant any more
