### ISSUE TITLE
Improve apiTestHelper for Storage UI tests

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1434]
_Related to the enabling of Storage UI tests in #1283_

Currently the **storage ui apiTestHelper** is not working reliably enough for us to build CID pinning tests and we need to add the ability to delete buckets too so that we can begin a bucket creation test with a clean data state.

Task: 

1) Investigate and determine wether `clearPins` is currently broken (and fix if it is) or clarify it is working but the deletion of CIDs is not instant because of the queuing system that we have with CIDs. 

2) Add the ability to delete buckets in the test helper so that we can clear bucket state prior to the test beginning for reliable bucket tests.

**Comment by Tbaut** [comment]
The apiHelper has the same problems on Files and Storage, the UI is working reliably, but direct calls to the api are actually making our life difficult for the following reason: the UI isn't reactive, when you do something such as creating/deleting a pin with the api, the UI won't update, because it's not subscribed to api changes. The reason why it works when e.g you're creating a pin with the UI is because the UI actually refreshes the list of pins after the creation.

So what can we do:
1.  somehow reload the page (we tried, cy.reload, but it's tedious)
1. navigate away and come back (using the nav for instance) which has the side effect of reloading the list: that's hacky but it works
1. have a refresh button on the interface that we could click? : that's building a feature just for the test.. not really advisable.

I'd go for the 2.

**Comment by asnaith** [comment]
> The apiHelper has the same problems on Files and Storage, the UI is working reliably, but direct calls to the api are actually making our life difficult for the following reason: the UI isn't reactive, when you do something such as creating/deleting a pin with the api, the UI won't update, because it's not subscribed to api changes. The reason why it works when e.g you're creating a pin with the UI is because the UI actually refreshes the list of pins after the creation.
> 
> So what can we do:
> 
> 1. somehow reload the page (we tried, cy.reload, but it's tedious)
> 2. navigate away and come back (using the nav for instance) which has the side effect of reloading the list: that's hacky but it works
> 3. have a refresh button on the interface that we could click? : that's building a feature just for the test.. not really advisable.
> 
> I'd go for the 2.

Yeah I think option 1 is the most logical but like you say we have experienced issues so option 2 is probably what we will have to do, at least for now. 

With regards to storage ui specifically there is still the behaviour of non-instant removal of pinned CIDs which is going to cause us problems even with a page refresh / nav away & return. When we are using the helper to clear pins at the beginning of a test (so that we can assert the correct number are added) the pinned CIDs might not have deleted by the time we want to begin. There's an indeterminate period of time before it's fully removed so we wouldn't know when to do the refresh.

**Comment by Tbaut** [comment]
> When we are using the helper to clear pins at the beginning of a test (so that we can assert the correct number are added) the pinned CIDs might not have deleted by the time we want to begin.

We should count the ones that are in "pinned" status, and forget about the "queued". Then the deletion isn't a problem any more.

**Comment by asnaith** [comment]
@Tbaut Ah yes, good suggestion and workaround

**Comment by Tbaut** [comment]
implemented in https://github.com/ChainSafe/ui-monorepo/compare/fix/test-not-updated-after-cleaning?expand=1

**Comment by asnaith** [comment]
@Tbaut @FSM1 This is definitely lower priority stuff but wanted to re-familiarize myself with this to see why more storage tests were not running...

It seems like we'd still need to implement similar apiTestHelper work for storage. I think the improvements we made recently were for Files only. 

At the moment we can't successfully clear buckets in our test setup, this is a pre-requisite.

I'm happy to take a go at it if someone can give me some pointers on where to start (as I think it's more than just copying over the same apiTestHelper from Files). Or should we leave this as-is for now and re-visit with dev assistance once higher priority work has been completed?

**Comment by Tbaut** [comment]
I would honestly leave this on the side for now. There are things that we can test and spend time on with higher priority such as Shared folders.
