### ISSUE TITLE
Validate the amount of characters before submitting a username

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1443]
The api limits the amount of char upon submission (currently 10 but should be updated), the api lookup looks good regardless of the amount of chat though, we should have a client side validation to prevent having an error after the submission.

**Comment by kalambet** [comment]
@Tbaut what do you think if we create appropriate API side issue issue and update to username limit up to 32 symbols.

**Comment by Tbaut** [comment]
Yup, sounds great thanks Peter.
