### ISSUE TITLE
Current Product Widget

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/files-ui#1454]
**Is your feature request related to a problem? Please describe.**
The widget that indicates the user's current plan with links to the subscription management modal needs to be created.

**Describe the solution you'd like**
The component should be pretty simple, just some buttons for navigation within that settings page, storage usage components exists in the codebase already. Clicking change plan should trigger the plan selection modal in #1455 

When the user is on a Basic plan, the `Cancel` button should be disabled.

**Additional context**
![image](https://user-images.githubusercontent.com/10461622/129879898-bd6cb139-c05f-4b47-8161-0e5972aa93a2.png)

**Comment by RyRy79261** [comment]
@tanmoyAtb @FSM1 @Tbaut Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1454?planning-poker)

**Comment by FSM1** [comment]
Looks like the % calculation for space used is going wrong. This is a pre-existing issue, but should be fixed in the same PR.

![image](https://user-images.githubusercontent.com/12774278/130642916-782cca5c-8188-444f-b379-e776195b8c31.png)

**Comment by RyRy79261** [comment]
@FSM1 roger that 

Just an update, waiting for the subscription end point to get plan data

**Comment by RyRy79261** [comment]
@FSM1 So I checked the percentages, its correct

Your example of 83.21mb is not even 1%  of 5Gb
For example, heres my used and total storage values

8403322    / 
5368709120 

= 0,00156524069607 
* 100
= 0,156524069607 %

**Comment by FSM1** [comment]
> @FSM1 So I checked the percentages, its correct
> 
> Your example of 83.21mb is not even 1% of 5Gb
> For example, heres my used and total storage values
> 
> 8403322 /
> 5368709120
> 
> = 0,00156524069607
> 
> * 100
>   = 0,156524069607 %

![image](https://user-images.githubusercontent.com/12774278/131704665-6cbebf86-0547-4bd8-96f0-1798eef44c9b.png)

The 100% shown is just wrong. The progress bar and actual usage are fine
