### ISSUE TITLE
Change plan summary

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/files-ui#1456]
**Is your feature request related to a problem? Please describe.**
The plan selection overview screen needs to be created, this screen takes data from the plan selected in #1455 

All details referencing Teams or price by team members or features should be ignored

Price data will come from the API, copy will come from the data described in #1455 

**Additional context**
![image](https://user-images.githubusercontent.com/10461622/129888663-a35b7f02-de70-4e80-b4b8-a5b499b4cb37.png)

**Comment by RyRy79261** [comment]
@FSM1 @tanmoyAtb @Tbaut Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1456?planning-poker)

**Comment by FSM1** [comment]
On ice until the Teams/Enterprise features are launched.
