### ISSUE TITLE
Unsubscribe modal 

### ISSUE THREAD

**Issue by RyRy79261** [ChainSafe/files-ui#1457]
**Is your feature request related to a problem? Please describe.**
The unsubscribe modal needs to be created, which is accessed by #1454, one edge case is that anyone on a free plan cannot cancel their plan, additionally, if a user has more files presently than the free plan has available storage, a warning should be shown in the modal, that the user should ensure that they are below the free plan limit before the end of the current billing cycle, and that their account may be deleted if they do not clear out enough files from their drive after `n` months

**Additional context**
Downgrade available:
![image](https://user-images.githubusercontent.com/10461622/129892510-c80ba8a0-2f16-4536-809e-d1f2fe35958c.png)

**Comment by RyRy79261** [comment]
@tanmoyAtb @FSM1 @Tbaut Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1457?planning-poker)

**Comment by FSM1** [comment]
Closing this in favor of handling any subscription changes on the `Select Plan Modal` in #1455
