### ISSUE TITLE
Generating a sharing link

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1473]
Bucket owner can generate a link - 
1. Accept input of # of uses, as well as target user permission (writer/reader)
1. Request NONCE from API
2. Generate JWT (containing nonce), and sign this with the user's Private Key
3. Create a link containing all the required data - Signed JWT, Folder Symmetric encryption key
4. Display this for the user to copy

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1473?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by sweetpea22** [comment]
https://www.figma.com/proto/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?page-id=2349%3A59153&node-id=4321%3A61125&viewport=241%2C48%2C0.07&scaling=min-zoom&starting-point-node-id=4321%3A61125

Flow link ^

**Comment by Tbaut** [comment]
@sweetpea22  So this is what isn't possible, we haven't created the new shard folder at this stage, so we can't create a link. It needs to be in a separate step unfortunately.
![image](https://user-images.githubusercontent.com/33178835/136234229-8cebc1a3-7384-4e14-9282-37b549d1896e.png)

**Comment by sweetpea22** [comment]
Trying to give our users a good sense of what's going on, i'll keep iterating on this 🧐
<img width="572" alt="Screen Shot 2021-10-06 at 10 29 47 AM" src="https://user-images.githubusercontent.com/47398578/136235101-49cdd02e-faf1-4d00-8f43-cca7676c5adf.png">

**Comment by FSM1** [comment]
Closed in #1603
