### ISSUE TITLE
Join share by opening a shared folder invite link

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1474]
A user who receives this link (after login) is directed to a page that will parse this link, extract the encryption key, encrypt the key with their pubKey.

In the event of a user not being logged in the login page should notify the user that they need to log in to access the shared content.

This page will then make an API request presenting the encryptedEncryptionKey, and the JWT.

The API will validate the JWT, make sure it was signed by the Shared Folder owner, and if all this info matches up, then the user making the request is added to the share.

The app would redirect the user to /shared/{bucketId}/

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1474?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by sweetpea22** [comment]
So if i'm getting this right, under all circumstances a user must create a files account to view content from a shared link. And this is considered technically publicly accessible as long as the user has a files account. Is that correct?

**Comment by FSM1** [comment]
Thats right - the link is an "permission slip" to our backend instructing it to add the bearer to the list of readers/writers of a particular bucket. Before this token can be utilized a user needs to have a key pair associated with their credentials, which can only happen after registration.

**Comment by sweetpea22** [comment]
Text content is changed on the auth screen, and redirects to folder once sign up/sign in is completed, I assume
<img width="1069" alt="Screen Shot 2021-10-06 at 9 51 41 AM" src="https://user-images.githubusercontent.com/47398578/136228139-d1c3dc53-d9f3-4180-b4d9-324d97d15769.png">

**Comment by Tbaut** [comment]
Not sure what we want to show once we passed the login, maybe a dedicated page with a loader "you're being added to XYZ"
And then "success" with a link to the shared folder?

**Comment by FSM1** [comment]
Closed in #1620
