### ISSUE TITLE
Migrate any usage of localstorage for user interaction to api user storage

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1486]
We are using flag now for
- Sharing explainer
- Survey dismissed

We should migrate them to user storage object, exposed on the UserContext. Linked to https://github.com/ChainSafe/files-api/pull/1427

**Comment by RyRy79261** [comment]
Endpoint PR is currently in Review, will intergrate when done

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1486?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
