### ISSUE TITLE
Survey banner displayed incorrectly on Safari

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1490]
**Description**
Noticed a minor issue with the display of the survey on banner on Safari, it's much larger than it needs to be. 

**Steps to Reproduce**
View the home screen of Files in Safari (mobile or desktop) with a user who hasn't dismissed the survey banner

**Observed behavior**
![IMG_613DACCA9FEF-1](https://user-images.githubusercontent.com/3982665/131927132-05e255d3-9d8c-4307-8595-0b84e0c47b9e.jpeg)

**Mobile:**
 - OS: iOS 14
 - Browser: Safari
 - Device: iPhone 12 Mini
 -
**Desktop:**
 - OS: macOS 11.5.2
 - Browser: Safari

**Comment by RyRy79261** [comment]
@asnaith Not sure how to replicate on my end. FF & Chrome appears fine when emulating

**Comment by Tbaut** [comment]
Tested on a real phone with chrome and it is displayed fine. I guess that's safari doing some weirdness. Could you check on another browser just to confirm @asnaith 

![image](https://user-images.githubusercontent.com/33178835/131992089-ca6435b6-f59e-4f20-8623-f5d0e96eef7c.png)

**Comment by asnaith** [comment]
@Tbaut @RyRy79261 So it looks like it's Safari specific rather than screen size specific. I can see the issue in Desktop Safari too. I've updated the original description to reflect this. I also can't replicate it on any other browser or using an emulator. 

<img width="2528" alt="Screen Shot 2021-09-03 at 11 01 21 AM" src="https://user-images.githubusercontent.com/3982665/132048346-7c32643a-12ca-464c-800a-64a3ef37dbb7.png">

**Comment by tanmoyAtb** [comment]
Got to reproduce this on my safari, looking into a fix!
