### ISSUE TITLE
Inconsistencies whilst trying to add multiple files to modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1506]
**Description**
There's an inconsistent behaviour whilst trying to add additional files for upload via this modal:

<img width="624" alt="Screen Shot 2021-09-08 at 1 21 05 PM" src="https://user-images.githubusercontent.com/3982665/132579757-b32c0755-5e64-4ca8-9829-07faa390069f.png">

**Steps to Reproduce**
1. Login to files
2. Click the upload button and choose a file
3. Click the "Add more files" button and attempt to add an additional file to the modal

**Observed behavior**

- On chrome: After the selection of the first file, each attempt to add more requires the user to select a file twice.

- On safari: After the selection of the first file it's not possible to add any more to the modal.

**Expected behavior**
The user should be able to attach additional files as necessary without having to make 2 attempts. 

**Videos**

Chrome behaviour (observe that it requires the additional file to be selected twice as the file picker is shown again after the selection): 

https://user-images.githubusercontent.com/3982665/132580441-cbe1ee99-1faa-4b4d-96bf-01f2f8ed9371.mov

Safari behaviour (observe it is not possible to add more than one file to the modal):

https://user-images.githubusercontent.com/3982665/132580473-45d0ae50-b560-4c2a-8676-7c7d1ed30ca8.mov

**Desktop:**
 - OS: macOS
 - Browser: Chrome / Safari
 - Version : 93.0.4577.63 / 14.1.2 (16611.3.10.1.6)

**Notes**
- Works as expected if adding multiple files at once (ctrl + click selection) 
- Works as expected for drag and drop
- Works as expected in firefox

**Comment by Tbaut** [comment]
Thanks, I can reproduce on Brave, not on FF.
