### ISSUE TITLE
Sharing multiple files, or a folder at once

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1509]
Feature request to  allow sharing of several files, or even a folder from the file menu, or the bulk action buttons.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1509?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
