### ISSUE TITLE
Login loading modal overlaps the logo 

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1510]
Screen size: 1178x796

<img width="1676" alt="Screenshot 2021-09-09 at 9 10 58 PM" src="https://user-images.githubusercontent.com/10713353/132713113-89740188-ea1f-441a-be27-559aa83adfca.png">

**Desktop
macOS, chrome

**Comment by Tbaut** [comment]
This is something Andrew mentioned a while back, that I've personally seen forever, but never took it as a bug.
See hi issue: https://github.com/ChainSafe/ui-monorepo/issues/1372

**Comment by tanmoyAtb** [comment]
> This is something Andrew mentioned a while back, that I've personally seen forever, but never took it as a bug.
> See hi issue: #1372

I missed that issue completely!
This will simply be reducing the height of the screen that shows the loader, that should accomodate for most screen sizes,
It was just bugging me a lot on my screen size and so opened it!
