### ISSUE TITLE
Create / Manage shared folder - drag and drop users between Readers/Writers

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1523]
**Is your feature request related to a problem? Please describe.**
There is no easy way to move already added users between the Readers and Writers tag input. Currently the owner would have to delete the tag from the one, and then add it to the other manually.

**Describe the solution you'd like**
Allow the owner to Drag & Drop tags between the Reader & Writer tag inputs

![image](https://user-images.githubusercontent.com/12774278/133240996-e8214647-8ae7-4304-8ad6-39a3544cc700.png)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1523?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
I'll close this one for now since it's not something particularly asked by a user, and it's far from trivial to implement.
