### ISSUE TITLE
Changes to top navigation elements

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/files-ui#1543]
<img width="1204" alt="Screen Shot 2021-09-20 at 1 29 06 PM" src="https://user-images.githubusercontent.com/47398578/134054998-3b051365-86c4-429a-bce0-c30cc53bec88.png">

Requested changes:
- Change all button text to `fontWeight: 600`
- Search bar is getting shorter
- two new buttons are `background: palette.additional["gray"][3]` 
- Report a bug button goes to our discord channel 
- Start a team is a fake door, will follow up with an issue for that modal 

On mobile we'll add them to the sliding out sidebar under "account".

Here's the calendly link for users to book a chat with us (replacing the survey banner): https://calendly.com/colinschwarz/chainsafe-files-chat

**Comment by Tbaut** [comment]
A small thing, but taking a lot of space right now is the breadcrumb. It's not visible on this design, although the reality shows a home icon, a bit lonely.
![image](https://user-images.githubusercontent.com/33178835/134158600-5274f775-e9ec-4dfa-b4ed-ec064e06c8ba.png)


> Report a bug button goes to our discord channel

This means we remove the one at the bottom right.

I've noticed the home icon doesn't show on shared and bin, maybe it'll be ok to remove it for now for homepage as well. 

And correct the bottom right button can be removed.

**Comment by Tbaut** [comment]
Also the calendly banner is already out. Just the color changes.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1543?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
