### ISSUE TITLE
Use more accurate toast messages for delete actions

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1546]
**Description.**
At the moment we have 3 different toasts that all display "File deleted successfully" 

- When deleting a file / folder from the home
- When deleting a file / folder from the bin
- When deleting a file / folder  from a share

**Describe the solution you'd like**
I think it would be better to only use "File deleted successfully"  when removing a file / folder in the bin and have unique strings for home / share folder deletions that are more accurate to the action.

E.g

"File moved to Bin" 
"Shared file moved to Bin" 

(or something better!)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1546?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
