### ISSUE TITLE
Incorrect font colour on share file modal (dark mode)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1547]
**Description**
- It's possible to type in the share drop down input in order to quickly find an existing shared folder but the text is too dark to see clearly

**Steps to Reproduce**
1) Login to files with dark theme enabled
2) Attempt to share a file
3) Type in the drop down selector to quickly locate the folder you want to share too

**Screenshots**

<img width="794" alt="Screen Shot 2021-09-17 at 11 16 26 AM" src="https://user-images.githubusercontent.com/3982665/134091695-f2f46727-0425-4da5-81f4-a61821762c4b.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 93.0.4577.63

**Comment by Tbaut** [comment]
I'd add to that the fact that the suggestion panel is hard to see (even in light mode)
