### ISSUE TITLE
Fake Door for Teams 

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/files-ui#1554]
<img width="1051" alt="Screen Shot 2021-09-21 at 1 42 29 PM" src="https://user-images.githubusercontent.com/47398578/134228989-4b4ee98b-4888-40e9-9ef2-fadd43946fcc.png">

This view is meant to validate interest in our team features. To separate those who are truly interested from those clicking a novel button, we added a button "Sign me up!" which takes us to a 1 question blocksurvey form to optionally leave contact information. 

I suppose we'll want to track the click through rate of the button and compare that to our DAU.

**Comment by Tbaut** [comment]
@ColinSchwarz I'll aim to count (1) the CTR of the "Start a team", then (2) the CTR of the "Sign me up", and then (3) we can count the number of emails we have. This way we can see if ppl are really only curious about the team button (1), and then if they're really willing to go further, and then see if they're reluctant to give their email to get informed.

Can you give the url of the Blocksurvey please @sweetpea22

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1554?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
done in #1587
