### ISSUE TITLE
Owner cannot rename shared folder

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1563]
**Describe the bug**
An owner cannot rename a shared folder. 

This looks like a regression bug as it seems like we previously fixed it in the past (see https://github.com/ChainSafe/ui-monorepo/pull/1197)

**To Reproduce**
1. Log in to files
2. Create a shared folder
3. Attempt to rename the shared folder you just created

**Expected behavior**
An owner should be able to change the name of the shared folder

**Video**

https://user-images.githubusercontent.com/3982665/134435236-651de7e4-58cd-47f7-8058-6a2dd5a0b2f2.mov

**Desktop:**
 - OS: macOS
 - Browser: Chrome (not browser specific)
 - Version : 93.0.4577.63

**Comment by Tbaut** [comment]
hmm there's something that went wrong with the api I think, the console shows. I'll ask.
```
 { type: "encryption_key", message: "Encryption key is a required field" }
```

**Comment by Tbaut** [comment]
From our conversation, this looks like an api error, we're providing what is requested. I'll keep this one open but we'll probably not have to do anything.
