### ISSUE TITLE
Display current links for a shared folder and allow to revoke them

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1593]
For the owner of a shared folder, it is possible to create a link sharing for this bucket.
The "Manage bucket" modal should show any link sharing currently active, and allow the owner to delete them.

needs clarification: We should actually also let an owner create a link after the folder creation, most probably at the same place. We could have a dedicated issue for this.

Note - This issue does not include the changes to how existing share users are displayed, only the display/copying of a link.

**Comment by sweetpea22** [comment]
User opens manage share and has an active link. If no link is active, link management modal still appears, but "active link" line will change to "copy link" or "generate link".  
<img width="1373" alt="Screen Shot 2021-10-06 at 9 47 55 AM" src="https://user-images.githubusercontent.com/47398578/136227406-47f33df1-f377-4b2b-81d8-1dbcc90bb1da.png">

If user retroactively adds edit permissions to an active link, we can indicate state change with button text content changing or color change.
![Edit link](https://user-images.githubusercontent.com/47398578/136228558-20715e43-4e16-4316-a199-4683419ee2b4.png)

Manage members can look like this, as the tag input could get unruly when lots of people are involved. Full access gives edit rights, plus share rights.
![Permissions toggle](https://user-images.githubusercontent.com/47398578/136228561-e5826071-162e-40b1-85db-1c96356e6b30.png)
![Remove user](https://user-images.githubusercontent.com/47398578/136228563-853d6904-64df-42e6-897a-95c767dbeeff.png)

open to changes as always

**Comment by Tbaut** [comment]
This is a pretty big change, on top of adding the link sharing feature. I'll tackle the redesign in a separate issue I think.
Also just a nit, but we said the "Full access" can't be given to someone this way, at least not for now.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1593?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
Another suggestion @sweetpea22, we can have several links, say one for view only, the other for edit. So the design should maybe cater for several links. Could we have all the important things on 1 line
- link (truncated) - permission dropdown - Button to copy link - X to revoke ?

Also we don't have any other toggle in the UI, and I'm not sure this is well suited, when for the same permission setting, we have 2 different UI elements (a toggle and a dropdown)

**Comment by sweetpea22** [comment]
> Also we don't have any other toggle in the UI, and I'm not sure this is well suited, when for the same permission setting, we have 2 different UI elements (a toggle and a dropdown)

Right, so I think toggle only makes sense if we republish permission changes to a single link because then users can be sure that one-click switch applies to the one link. But if we have multiple links it would make sense to use this dropdown, gives a better sense of differentiating what is selected. I'll get back to you with examples like you described

**Comment by Tbaut** [comment]
Nice thanks! Looking at something like this, maybe with a button to create a new link as well
![image](https://user-images.githubusercontent.com/33178835/136265044-aceeaada-6c29-4539-93bf-7235315fb692.png)

**Comment by Tbaut** [comment]
I'll change this slightly, because changing the permission of a link is actually not supported, so I'll prevent this from happening, and just make sure the permission is set at the creation

**Comment by Tbaut** [comment]
@sweetpea22 I'll submit a PR with the following, let's make it nicer then :)

https://user-images.githubusercontent.com/33178835/136352400-edbd8912-82f6-4d7d-b0fc-05c5b04e5558.mp4
