### ISSUE TITLE
Allow users to control whether they can be looked up by wallet address

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/files-ui#1601]
The account details screen should have a checkbox to allow a user to enable the `lookup by username/wallet address` feature for their account.

**Comment by Tbaut** [comment]
Wallet address can be used any time, there was this little quirk that it could only be used when there's a username set as well. This should be logged and get a fix on the api side. I dug a little but couldn't find the issue in the api repo. Could you give us the link @dhyaniarun1993 or @ohmpatel1997 ?

If the user logs in with email/oauth provider, they can't use the email as sharing medium.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1601?planning-poker) with ZenHub @tanmoyAtb @Tbaut
