### ISSUE TITLE
Lighten the colour of menu component (dark mode) 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1614]
*suggestion* 
Lighten the colour of the menu component so that it is more distinguishable in dark mode. 

*screenshot*
This is how it currently looks: 
<img width="256" alt="Screen Shot 2021-09-24 at 10 16 16 AM" src="https://user-images.githubusercontent.com/3982665/136105596-9ea69f3a-2bec-4c7b-bd53-d5a3518957f3.png">

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1614?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
