### ISSUE TITLE
Update the sharing tutorial to talk about links

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1629]
Right now, the sharing tutorial only talk about adding ppl to a shared folder. We could think about adding a mention of link sharing? wdyt @sweetpea22 @serenaho ?

to be precise, I'm talking about this "tutorial"
![image](https://user-images.githubusercontent.com/33178835/137304270-f9981f0b-64e3-483a-a1d5-2d32a9120429.png)

**Comment by sweetpea22** [comment]
Great thinking Thibaut as always :) 
Let me get a graphic for you once I'm done with flow

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1629?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by FSM1** [comment]
Another thing to add is the lookup flag

**Comment by Tbaut** [comment]
@sweetpea22 or @serenaho any chance we can have a design for this?

@FSM1 we can talk about the lookup flag on the slide "add by name" wdyt?

**Comment by sweetpea22** [comment]
Just to make sure, you need a graphic that shows adding people to shared folder. Or something different?

**Comment by Tbaut** [comment]
I updated the OP description which wasn't clear, sorry about that. We want to talk about sharing links, so something with a link icon, and a folder maybe?

**Comment by serenaho** [comment]
Thanks for being patient-- Do any of these options stand out in terms of communicating link-sharing?

![image](https://user-images.githubusercontent.com/91699405/144639882-b2e56dd1-b455-42df-96a6-9e5041a3d6a6.png)

**Comment by Tbaut** [comment]
:heart: this is tough, they are all very good. I'd go for A if you ask me.

**Comment by Tbaut** [comment]
![Link-Sharing Tutorial](https://user-images.githubusercontent.com/33178835/146654399-e1e77400-7c3c-4c4e-b5a0-d103437711b3.png)
