### ISSUE TITLE
Make link creation design nicer

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1630]
I came up with this design, it's not ideal I guess. Let's brainstorm and find its flaws and come up with something better

Some [comments](https://github.com/ChainSafe/ui-monorepo/pull/1619#pullrequestreview-775057022) from @tanmoyAtb 
> This one is about preference, I would like to have the Create new Link button on the right side of permissions dropdown, feels more natural to me. (I haven't seen the designs though).

I guess my buttons are just too big?

https://user-images.githubusercontent.com/33178835/136352400-edbd8912-82f6-4d7d-b0fc-05c5b04e5558.mp4

**Comment by alexmmueller** [comment]
This looks great! Just a small hint: I think "read rights" is not really native language, or?!? I would suggest something like " 
 'Create new Link' and allow to <read/ edit>" ...

**Comment by Tbaut** [comment]
Sure anything that sounds more right is good.
Note that the video shows the current implementation, which we consider "not good" enough, hence this issue to make it better.

**Comment by Tbaut** [comment]
The design are almost ready here https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=2349%3A59153
![image](https://user-images.githubusercontent.com/33178835/138888139-7ea0c8de-1ec7-46fb-9739-3091335adafa.png)

**Comment by FSM1** [comment]
![image](https://user-images.githubusercontent.com/12774278/140096017-e7d2f65d-5d2e-475b-8770-f7b4e7100abc.png)

**Comment by FSM1** [comment]
Restrict creating links to ones which have not been created yet - The user can only have 2 links (1 read, 1 write), so the link creation part of this dialog should be intelligent enough to only allow the user to create links that they do not have yet.

If a user has 2 links they should not be allowed to create any more.

The 2 section modal will also require some rework on the CustomModal.tsx component, to accomodate this layout.
