### ISSUE TITLE
Allow link creation when sharing files

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1631]
One should be able to create a sharing link to share a shared folder.

The current design in Figma [here](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=4397%3A90289).

The first step would be to either select an existing folder, or to create a new shared folder. The sharing method would be the second step only in the case that we create a shared folder. 

So here are the flows:
- step1: Select either 1) an existing shared folder 2) create a new shared folder and give it a name
  if 1) then a click on "Share" would start the DL/encryption/UL
  if 2) then go to next step
- step2: We launch the DL/encryption/UL in the background and allow users to manage access with name/sharing link.

![image](https://user-images.githubusercontent.com/12774278/141156622-65922554-70a1-4b3d-b868-5a79a8163d78.png)

**Comment by FSM1** [comment]
Attempt to reuse the Manage Access component for the User selection.

Add a Posthog hook to analyze whether the `Keep files/Move files` is actually used.

**Comment by FSM1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1631?planning-poker) with ZenHub @RyRy79261

**Comment by asnaith** [comment]
I just realised that it's all file types that don't preview now on iOS. Not just video. 

https://user-images.githubusercontent.com/3982665/142077378-ff5b15ec-4d8c-4921-b7e2-da71af5071a2.MOV
