### ISSUE TITLE
Unhandled exception: Missing or invalid topic field

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1639]
I'm getting an unhandled exception when changing wallet on Storage and Files, `Unhandled Rejection (Error): Missing or invalid topic field.`

Here is how:

continue with web3 wallet
connect a new wallet (was metamask originally)
chose walletconnect
closes 2 popups
click to connect with another wallet to select metamask -> the error appears.

**Comment by FSM1** [comment]
This is most likely related to the ERC20 Balance watcher component of the Web3 Context, and as such should be addressed there.

**Comment by Tbaut** [comment]
Closing as I've not had it in ages.
