### ISSUE TITLE
User Dropdown restyle

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1647]
- User menu moved to sidebar
- User Identicon as per the screenshot below, colored generatively (Can probably use the user's UUID for the seed data).
- Clicking on the item will open a menu allowing user to log out

See [figma](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=4297%3A60807)

![image.png](https://images.zenhubusercontent.com/5f21c3ad1a888957863fd321/65a1da0d-3326-4428-9542-76167a749335)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1647?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
Just a comment UI-wise for @sweetpea22 and @serenaho This is not obvious that the nickname is actually a drop-down. I think there should be an arrow or something. Or we could move the logout out and place it in the manu bar?

**Comment by FSM1** [comment]
> Just a comment UI-wise for @sweetpea22 and @serenaho This is not obvious that the nickname is actually a drop-down. I think there should be an arrow or something. Or we could move the logout out and place it in the manu bar?

I think that since it is styled like a button it should be fairly obvious to the user that there is some kind of action attached to the element...
