### ISSUE TITLE
Update Product plans page link in select plan

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1654]
After creation of plans pricing and description page,
We should add the link to the Change plan modal in Subscription settings

It's in `ROUTE_LINKS.ProductPlans` from `packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx`

**Comment by FSM1** [comment]
@sweetpea22 I am guessing the pricing page still needs to be added
