### ISSUE TITLE
Remove API version from request intercepts

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1655]
@Tbaut made a good point that the current tests where we are using api stubbing are brittle because we include the full path of the key that is version specific, meaning whenever we update the version of the key we will break the tests.

**Comment by FSM1** [comment]
Honestly do not think that we will be changing that version string in the API any time soon. If we were to release a major new version, this would likely run in parallel with the V1 API for some time still and would involve so much refactoring in other parts of the system that the tests would likely need to be updated in any case.

**Comment by Tbaut** [comment]
Yup the api version isn't an issue. The survey banner version is what my comments pointed at https://github.com/ChainSafe/ui-monorepo/pull/1648#pullrequestreview-787903772

**Comment by FSM1** [comment]
> Yup the api version isn't an issue. The survey banner version is what my comments pointed at [#1648 (review)](https://github.com/ChainSafe/ui-monorepo/pull/1648#pullrequestreview-787903772)

ahhh ok that makes a lot more sense 💡

**Comment by asnaith** [comment]
I was under the impression it was regarding the version in the URL until drinking more coffee and reading Thibaut's comment again 😄. Ultimately it's probably best to stip version specifics from url and key.
