### ISSUE TITLE
New Folder button icon not responsive

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1663]
Inside a shared folder, the **New folder** button has an unresponsive icon that shrinks when window is resized.

![Screen Shot 2021-10-27 at 10.23.39 AM.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/b8088d91-23cb-4eb8-8afe-5f2fab24199f)

In addition, when the two buttons combine into a single menu the name for it changes from **New folder** to **Create folder**. This issue is the same across all of the pages (Home, Shared, etc.).

![Screen Shot 2021-10-27 at 10.24.12 AM.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/5a5b53c2-859a-4d38-a98b-3fb358fe9529)

_Suggested solutions:_
Make the icon responsive, and keep the name consistent by using **New folder** in all menu's.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1663?planning-poker) with ZenHub @Tbaut @tanmoyAtb
