### ISSUE TITLE
Modals cut off at the top (mobile)

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1664]
Modal #1: When opening the **Info** menu item in _mobile landscape orientation_, the modal is cut off at the top of the screen with no option to scroll up to see the whole thing. 

The swipe-up gesture moves the background content instead (see gap above **Close** button).

https://images.zenhubusercontent.com/285884697/39c73530-bf2e-4701-9f8d-cbf6f6beea3d/info_modal_cut_off.mp4

Modal #2: Same issue but with the **Share** menu item.

![Screenshot_20211027-105626.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/c44fefe1-00a2-4a28-8a15-6ab57eaa9719)

**Comment by Tbaut** [comment]
I believe this is a general absolute positioning problem for all the modals.

**Comment by FSM1** [comment]
Could be quite a significant change to enable this. Investigate whether the changes required to make this happen would be very significant, and if so, whether it makes sense to hold on with this until we settle down on the component library select.
