### ISSUE TITLE
No name header for table(s) (mobile)

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1672]
Mobile version of Files does not have name header for File Browser tables (or ability to sort content using alphabetical order like the desktop version).

![Screen Shot 2021-10-27 at 1.54.03 PM.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/c64e1762-9ce1-431b-b8c4-7c5fe16f4e67)

Suggested Solutions:
Add name header for consistency and implement alphabetical sort like below
![image](https://user-images.githubusercontent.com/12774278/143307601-11616a65-b2c0-46a3-b521-1b307335adc9.png)

When no items are selected (in the file browser), the 3-dot menu should allow the user to switch between various sorting options:
![image](https://user-images.githubusercontent.com/12774278/143307692-feeadc5c-d118-4d1d-bc94-f44ed6e7917e.png)

The selected sorting option and direction should be displayed in the header of the first column.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1672?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
