### ISSUE TITLE
[a11y nits] Use sufficient contrast color for hover/focus 

### ISSUE THREAD

**Issue by sweetpea22** [ChainSafe/files-ui#1678]
This issue is a list of cosmetic nits to make our hover states more consistent and meet a11y standards.

### Changes requested

1. Currently, hover on sidebar item has this interaction:  
<img width="192" alt="Screen Shot 2021-10-29 at 9 44 44 AM" src="https://user-images.githubusercontent.com/47398578/139455570-5f441061-3a2b-46a2-96b0-2bcfec519bdd.png">

suggested change: a gray[4] background highlight when sidebar item selected and hovered: 
![Screen Shot 2021-10-26 at 7 34 1](https://user-images.githubusercontent.com/47398578/139456545-a89304c5-0e00-4155-87c6-e9063739b729.png)

2. Currently, rows in the file browser with the gray striped background don't show selection state when hovered over.
Suggested change: Make the hover row background the same shade as selected row background(gray[4]) 
<img width="525" alt="Screen Shot 2021-10-29 at 9 50 34 AM" src="https://user-images.githubusercontent.com/47398578/139456686-02c62ebd-a5a2-42aa-894a-b2e30a19745c.png">

3. Currently no interaction exists when hovering menu items in settings. It would be nice to add some hover interaction here. I'd also suggest to bump up the contrast when settings menu is selected by increasing font size to body1, font weight to `600` and making the icon a bit bigger. 
<img width="258" alt="Screen Shot 2021-10-29 at 9 45 39 AM" src="https://user-images.githubusercontent.com/47398578/139457055-450b0921-2193-4af7-bf50-a3643b4551ef.png">

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1678?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb
