### ISSUE TITLE
Overly Sensitive File Selection (Mobile)

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1682]
Content selection is very sensitive-- it is difficult scrolling up and down without selecting content along the way.

https://images.zenhubusercontent.com/285884697/3dc15153-0ceb-4f4b-bfb7-2960d9c40704/sensitive_file_selection__mobile_.mp4

**Comment by RyRy79261** [comment]
Just an update, this is being caused by the a mobile `long press` feature where its registering `touchend` as a selection, which is also emitted at the end of a drag action, Tanmoy is looking into it
