### ISSUE TITLE
Bin Still Clickable After Closing (Mobile)

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1683]
The Bin menu item from left navigation remains active on screen (even though it is invisible) when navigating to different screens.

https://images.zenhubusercontent.com/285884697/c4894974-9868-45b9-8f40-46bdb27017cf/faulty_nav___portrait__mobile_.mp4

**Comment by Tbaut** [comment]
@serenaho did you test this on a real device?
I tried both with Firefox emulation and with Firefox on android (real device) and couldn't reproduce. Is that on safari with iphone? Can you reproduce with safari on desktop as well?

**Comment by serenaho** [comment]
@Tbaut I discovered it while on google chrome with my google pixel 3 phone!

**Comment by serenaho** [comment]
I just did it again on desktop using google chrome and macbook:

https://user-images.githubusercontent.com/91699405/139727416-94e70e7c-b123-4c77-9f53-de29741e3009.mov

**Comment by Tbaut** [comment]
Ok I can reproduce on Brave. The menu is hidden (so anything in the menu, the Bin/Home/Shared, the settings etc.,), but can still be clicked for a second. Waiting a sec and the problem doesn't appear any more (the section becomes inactive). This looks like it's a transition issue.

**Comment by RyRy79261** [comment]
Tried on my mozilla, only when I manually set transitions to 0.25 speed could I grab it

In theory the window is 400ms for someone to do this

**Comment by FSM1** [comment]
What if we just render `null` if the drawer is closed?

**Comment by RyRy79261** [comment]
@FSM1 so the issue would be a bit of graphics popping, in theory, a pseudo-element as a click block could suffice
