### ISSUE TITLE
Language Dropdown Expands Beyond Display (Mobile)

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1684]
When selecting a different language, the dropdown expands below the screen and cannot be interacted with until you scroll up within the actual dropdown itself.

https://images.zenhubusercontent.com/285884697/1e720048-fe4e-4e00-a6d2-25550d5a0625/bottom_dropdown.mp4

**Suggested Solutions:**
Make the dropdown open upwards or allow user to keep scrolling down.

**Comment by RyRy79261** [comment]
Attempting to make the dropdown component have awareness of if its on certain quadrants of the screen and change the positioning dynamically, if its not solved quickly I'll set it to go upwards as an initial patch
