### ISSUE TITLE
Unintended padding / styling around side menu bar

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1688]
**Description**
The presentation of the side menu looks odd, it now has some extra styling / padding around it

**Steps to Reproduce**
Login to current stage environment

**Screenshots**

<img width="1466" alt="Screen Shot 2021-11-01 at 9 45 42 AM" src="https://user-images.githubusercontent.com/3982665/139708948-85624ce1-b924-4aa3-a2cb-5843e135e98c.png">

<img width="1470" alt="Screen Shot 2021-11-01 at 9 45 26 AM" src="https://user-images.githubusercontent.com/3982665/139708986-361ce4f7-32a3-4122-a4c6-ead7f53fa6e5.png">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version : 95.0.4638.54

**Comment by Tbaut** [comment]
on dev? Most prob related to https://github.com/ChainSafe/ui-monorepo/pull/1677

**Comment by Tbaut** [comment]
aaah I think that's the scrollbar. `overflow: auto;` should do the trick. Let me Pr that real quick
