### ISSUE TITLE
Menu options sometimes not displayed (Responsive Layout + Safari)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1699]
**Description**
The menu options on the mobile slide-out menu sometimes do not appear

**Steps to Reproduce**
1. Navigate to files on an iPhone (stage)
2. Repeatedly hide and show the menu

**Observed behavior**
See video 

**Expected behavior**
The menu options should always be displayed 

**Screenshots**

![IMG_3026](https://user-images.githubusercontent.com/3982665/140100621-2cadd94c-d8b0-49b4-8fbf-3c049b7356d3.PNG)

**Video**

https://user-images.githubusercontent.com/3982665/140100664-addccede-7ca1-444a-8d90-e1b940145665.MP4

**Desktop:**
 - OS: iOS 15
 - Browser: Safari

**Comment by asnaith** [comment]
This seems to be exclusive to Safari, I cannot reproduce in another browser and @serenaho has confirmed the issue does not happen on Android

**Comment by FSM1** [comment]
@asnaith any idea if this same issue is present in Safari on desktop (when emulating mobile)? I have attempted to replicate this in chrome on Windows, while emulating an iPhone, but still unable to cause this glitch.

**Comment by asnaith** [comment]
@FSM1 Ah yes, oops I meant to update this yesterday. 

I can reproduce in the desktop version of safari too when it's in the mobile layout. I've not yet been able to reproduce it in any other browser, just Safari on iOS / macOS. 

https://user-images.githubusercontent.com/3982665/140383935-da653c90-79b3-4719-8d4d-3a2f4d8d7d82.mov
