### ISSUE TITLE
Allow users to download a receipt as PDF

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1706]
Subsequent to https://github.com/ChainSafe/ui-monorepo/pull/1492 users should be able to download their invoice as pdf.
This requires back-end pdf generation

Make API call to request PDF for a specific Invoice ID
Download the PDF to device, and allow browser to save.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1706?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
