### ISSUE TITLE
File info modal - CID Copy Button & Encryption Key Copy Button

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#1720]
Remove the Copy CID button from below,
Add a copy CID icon button with the CID string.
Add a copy button for the decryption key

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1720?planning-poker) with ZenHub @RyRy79261 @tanmoyAtb @Tbaut
