### ISSUE TITLE
Error with signing in (up?) to Chainsafe Files, both with email and Metamask

### ISSUE THREAD

**Issue by adrien-mg** [ChainSafe/files-ui#1721]
Hi,

Hope you guys are well. I was keen to give a spin to Chainsafe Files but got stuck extremely quickly when trying to signing in (can't find a signing up option?).

```
OS: Archlinux
Browser: Firefox
```

### Attempt 1, with email

I tried with 3 different email addresses; I get a verification code, that I enter in the interface, only to get error message:

```
Something went wrong!
```

.. see file attached: `chainsafe-files-email-error`.

![chainsafe-files-email-error](https://user-images.githubusercontent.com/71636209/140944344-b9961a5b-7f7a-458f-a55e-bc5bd513250a.png)

### Attempt 2, with Metamask

I tried clicking on the Web3 Wallet option, which took me to my Metamask Firefox extension. After clicking and clicking, I finally get the error message:

```
There was an error authenticating
```

.. see files attached: `chainsafe-files-metamask-error-{1,2}`.

![chainsafe-files-metamask-error-1](https://user-images.githubusercontent.com/71636209/140944349-663fcf4a-ad57-466a-a2ea-57c41a1774ed.png)
![chainsafe-files-metamask-error-2](https://user-images.githubusercontent.com/71636209/140944348-612d04e2-888f-477a-81ae-d3fce2d38a9d.png)

Am I being thick for not find the signing up button maybe, or am I missing any other thing? I feel like this is not great user experience anyway.

Thanks for all the good software anyway!

Have a great day,
Adrien

**Comment by Tbaut** [comment]
Hi Adrien, there is no difference between sign-up and sign-in, but it's good to know that you expect such a thing.

Thank you so much for reporting the issues.

I couldn't reproduce the issue you have, and I guess there must be something going super bad with some calls being blocked maybe? I'm on Linux, and FF just like you. Using ublock origin as well. 

Any chance you could open the console (ctrl + shift + j) and tell me what you see there?

edit: also I see an "insert mode" on your screenshots. Is that some extension you use that could be blocking or interfering with the website?
