### ISSUE TITLE
Decryption key on "Report File" modal is cut off

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1726]
**Description**

![Report A File](https://user-images.githubusercontent.com/3982665/141210423-751b8132-8cbb-48cf-884a-fc9ac573f70d.jpeg)

**Notes**

Seems like the required changes could be very similar to the improvements made in #1720 and #1713 for the "File Info" modal

**Comment by FSM1** [comment]
There is an overflow scroll applied to the element

https://user-images.githubusercontent.com/12774278/142021282-d02d83c1-6498-4139-872a-7bebbf0417f1.mp4
