### ISSUE TITLE
Inconsistent style on modals (mobile) 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1729]
**Describe the bug**
I noticed that we have a variety of different modal styles in the mobile view. Sometimes we use rounded corners, sometimes flat edges. Sometimes a separate section for the cancel button and sometimes it's within the modal itself

**Screenshots**

Examples

<img width="1946" alt="Screen Shot 2021-11-10 at 4 12 56 PM" src="https://user-images.githubusercontent.com/3982665/141214710-9692d5ee-b758-40c6-a0f4-e6e74d27fb3a.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Mini
 - OS: iOS 15
 - Browser Safari

**Comment by asnaith** [comment]
@serenaho I logged this as I thought we might want to aim for some consistency across all modals but I also may be unaware of other plans in design etc. Do you have any advice on what would be best here?

**Comment by serenaho** [comment]
In terms of plans, Cindy and I will be auditing all Files components (very soon, ~next week!) in order to build a consistent design system. We will definitely be aiming for consistency across Files, especially with buttons and CTAs like this one. Thank you for bringing it up, I'll put this on my list!

**Comment by RyRy79261** [comment]
@serenaho Just need some clarity, what would the preferred appearance be here? :)

**Comment by serenaho** [comment]
> <img alt="Screen Shot 2021-11-10 at 4 12 56 PM" width="1946" src="https://user-images.githubusercontent.com/3982665/141214710-9692d5ee-b758-40c6-a0f4-e6e74d27fb3a.png">
> 



@RyRy79261 Let's use the same Cancel button in the left + middle screens to apply to the right modal for Create Folder.

To keep things consistent, I'd also remove the rounded edges from the middle + right modals. Thank you!
