### ISSUE TITLE
Copying anything to the clipboard doesn't work on mobile

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1733]
the `navigator.clipboard.writeText` is not supported by the latest chrome mobile on the latest android, and I think any safari mobile either.
An alternative (as implemented for testing in https://github.com/ChainSafe/ui-monorepo/pull/1722 is to use `document.execCommand("copy")` but it's deprecated! Still this is working cross-platform.

In any case, we should write a hook for this and reuse it everywhere we need to copy something.

**Comment by RyRy79261** [comment]
There's mentions of requesting permissions from WebView, the internal Android browser feature, though apparently requesting said permission is difficult. 

There's this link discussing a fix though it looks a bit foreign:
https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest

**Comment by FSM1** [comment]
I just tested in what I think is the latest version of Chrome  and Firefox on Android, and copying is working perfectly on PROD and STAGE
![image](https://user-images.githubusercontent.com/12774278/141991629-511fdb15-9601-432c-aa8a-58b3cbbedf21.png)

> There's mentions of requesting permissions from WebView, the internal Android browser feature, though apparently requesting said permission is difficult.

All of the above should only be relevant in apps which use WebView where the dev would need to access system clipboard API. Browsers already handle this by wiring up the `navigator.clipboard` API to the system clipboard API.

@asnaith have you noticed any issues with copying any data on iOS Safari?

**Comment by asnaith** [comment]
@FSM1 No, it seems fine. I haven't seen any issue with copying on Safari in iOS (prod and stage).

**Comment by FSM1** [comment]
> @FSM1 No, it seems fine. I haven't seen any issue with copying on Safari in iOS (prod and stage).

Ok I tested in Chrome/Brave/Firefox on Android and all seems to be working with the old `navigator.clipboard` api, so I am reverting the changes made by Thibaut, and will close this issue. We can always reopen the issue if it surfaces again.

**Comment by Tbaut** [comment]
Re-opening. It's definitely not working for me on a real device the latest Android 12 with the latest versions of Firefox nightly and Chrome :(

Could someone please triple check? I'm testing the copy button from the file info modal

**Comment by Tbaut** [comment]
ok it works on staging, but not on localhost:3000, :man_shrugging:

**Comment by FSM1** [comment]
probably related to localhost not using HTTPS
