### ISSUE TITLE
Share Explainer Modal - Close button position

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1734]
**Describe the bug**
Close button on modal is positioned outside of the modal

**To Reproduce**
1. Log in to the system with a new account/or force the explainer modal to show by fiddling with state
2. Navigate to Shared Overview

**Expected behavior**
Modal close button should be inside the modal

**Screenshots**
![image](https://user-images.githubusercontent.com/12774278/141323867-f4302f5f-b23b-45db-ad86-5e5c0af39b32.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 94

**Additional context**

**Comment by Tbaut** [comment]
Damn, I swear i checked it out (this one and the team fake door). Will take a look
