### ISSUE TITLE
Search dropdown has stray characters

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1787]
**Describe the bug**
There are random `0` printed in the search box.

**To Reproduce**
1. Log in and search for any string that does not exist.
2. Observe the `No results` message has `00` appended to it.
3. Search for a file that does exist
4. Observe a `0` in the top right corner

**Expected behavior**
No stray characters should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/12774278/143947179-3120b1df-f6d5-4543-bd8a-20df698b91f6.png)
![image](https://user-images.githubusercontent.com/12774278/143947214-6cfc29da-31a8-4268-b63a-d884da948ea3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 96

**Comment by Tbaut** [comment]
Will take a look, this happens when checking an array length I guess.
