### ISSUE TITLE
Show the latest bills and allow to download them from the subscription tab

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1808]
Follow the mock
![image](https://user-images.githubusercontent.com/33178835/144879960-bc2fb269-6690-4b59-8865-23550b376698.png)

Initiating payment on an unpaid invoice is out of the scope of this issue.

**Comment by FSM1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1808?planning-poker) with ZenHub @Tbaut
