### ISSUE TITLE
Nice notification image when there's nothing to show 

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1821]
It'd be great to have a nice little icon/drawing to show when there's no notifications to show to our users.

It doesn't have to be crazy, a simple icon as we have when there's no file to show is sufficient.
![image](https://user-images.githubusercontent.com/33178835/145253177-da161c92-4fc8-4788-8cb3-666bf267cc5e.png)

**Comment by serenaho** [comment]
A few options to choose from-- Icons and phrases can be interchanged depending on which one we like more:

![Empty Notif 1](https://user-images.githubusercontent.com/91699405/145486446-74412b8d-a648-46ac-aa7d-10754274cc5d.jpg)

![Empty Notif 2](https://user-images.githubusercontent.com/91699405/145486595-0619b0ef-1f4f-47e3-bbd9-2446f4d255ac.png)

![Empty Notif 3](https://user-images.githubusercontent.com/91699405/145486604-01ef9e59-bc5c-49b1-85a1-9608101ed93f.png)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1821?planning-poker) with ZenHub @tanmoyAtb @Tbaut
