### ISSUE TITLE
Awaiting payment (crypto) notification & status

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1846]
When a user went as far in the process than we opened a coinbase charge from the api side, e.g the user is expected to send some crypto to some address, right now we're in this state:
- the subscription we get from the api has the status "pending_payment"
- there's nothing in the UI that allows the user to go back to showing the QR code, the receiving address etc...

There's this, but I feel it's more for the case when there's a recurring subscription with a credit card or something https://github.com/ChainSafe/ui-monorepo/issues/1829 I would this not intuitive.
Talking with the design team, a good way to tell the user would be to show a spinner on the plan's button for the plan that got selected (and  that has the pending status). and name the button "awaiting payment".

The spinner is something somewhat used a lot by DEXs to convey the idea that something is in the way. On in case the user didn't send the payment yet, that it's being awaited.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1846?planning-poker) with ZenHub @tanmoyAtb @Tbaut
