### ISSUE TITLE
Extend apiTestHelper to programmatically remove cards

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1847]
*Summary*
At the moment we have no ability to remove the card associated to a user profile prior to beginning a test. This means we cannot reliably run our "add / update / remove card" tests.

Adding this functionality will give us the ability to always start the test in a clean state no matter what happened in previous test executions.

Acceptance Critieria: 

- Add new functionality to apiTestHelper.ts / commands.ts that gives us the ability to remove credit cards on the profile programmatically
- Update `cy.web3Login()` calls in `subscription-plan-spec.ts` to include new parameter for removing any pre-existing card. 
- Remove the `skip` on the `it` for the "can add, update and remove a credit card for billing" test.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1847?planning-poker) with ZenHub @tanmoyAtb @Tbaut @asnaith

**Comment by Tbaut** [comment]
that's done
