### ISSUE TITLE
Copy and style change for yearly/monthly payment

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1856]
I've found this a little hard to understand as we have right now a toggle with just the work "monthly" or "yearly". Also when the toggle is toggled, there's no way to see if it's active or not. If it's active, it should have color IMHO. 

All in all, I think we should stick to the design
![image](https://user-images.githubusercontent.com/33178835/149377575-d6936ec1-798c-422e-8f54-cc9363f23eeb.png)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1856?planning-poker) with ZenHub @tanmoyAtb @Tbaut
