### ISSUE TITLE
Extend apiTestHelper to programmatically set users subscription plan 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1865]
**_Summary_**

At the moment we have no ability to set a user's subscription plan level at the beginning of a test. 

Whilst the free plan is default and we use a unique user per test session we still need to put this in place because if a test fails after a user has been changed to a different plan then non of the automatic retries will work either. 

In addition to this, it would be great if we could also programmatically set a user to a standard or premium plan too. If this is possible it would help make future downgrade path tests more efficient. 

**_Acceptance Critieria:_**

- Add new functionality to apiTestHelper.ts / commands.ts that gives us the ability to set the subscription plan programmatically

**Comment by Tbaut** [comment]
While I don't think we can achieve what the issue is about, we can at least make sure the user is on the free plan, or set it to it. Because there is no payment associated to this move, and hence, no need for crypto or registered card.
