### ISSUE TITLE
Update Invoice Line Item

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1870]
The Invoice Line item should display the following info:
- Plan that is being paid for
- Duration of the plan
- Total amount charged to the user (instead of showing the plan price).

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1870?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by asnaith** [comment]
I noticed some minor alignment issues but other than that looks great. 

<img width="1309" alt="Screen Shot 2022-01-28 at 10 33 52 AM" src="https://user-images.githubusercontent.com/3982665/151603812-151f1e78-e43d-4e15-8b92-6176149d73a4.png">
