### ISSUE TITLE
Display additional subscription and card details

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1885]
The next billing date as well as card expiry date (if applicable) should be displayed to the user. The section heading should be updated as well.
![image](https://user-images.githubusercontent.com/12774278/151361584-5e4d359e-245d-47de-8d60-cff6b4858419.png)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1885?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by Tbaut** [comment]
the default card answer from the api has the expiry information, the next payment is available in the current subscription, there's a `expiry_date` field.

**Comment by Tbaut** [comment]
BTW where is this screen?
I can see if we add the expiry of the CC on the card payment, but I find it weird to have the next payment here. If it's where I think it's supposed to be, I think it might look weird:
![image](https://user-images.githubusercontent.com/33178835/151394695-4d4f71dc-d1a8-43dd-a82a-02c5640fa121.png)

**Comment by FSM1** [comment]
Yeah it would be pretty much where you had marked it off:
![image](https://user-images.githubusercontent.com/12774278/151444808-9d8c0074-be37-4853-9add-f3fcc1765176.png)

Looks fine on figma 🤷🏼

**Comment by Tbaut** [comment]
There are so many differences on Figma :see_no_evil: . We should have an issue to align, or modify this one to address those differences:
- The copy is different "Credit card info", rather than "Payment info"
- The plan info takes a good amount of space where everything is left aligned  in the implementation
- The design uses "button links" whereas we use buttons ("Change plan, Edit payment, View pdf, Pay now")

**Comment by tanmoyAtb** [comment]
We can have the style changes with this issue. The estimates would change of coarse.
Not sure about the features section in plan, We only have the difference of allowed storage in each plan and we're already showing that.

**Comment by FSM1** [comment]
> There are so many differences on Figma 🙈 . We should have an issue to align, or modify this one to address those differences:
> 
> * The copy is different "Credit card info", rather than "Payment info"
> * The plan info takes a good amount of space where everything is left aligned  in the implementation
> * The design uses "button links" whereas we use buttons ("Change plan, Edit payment, View pdf, Pay now")

Im updating the `view pdf` and `pay now` to be links in my PR already, and will also do the highlighting.

Happy to expand the scope of this to align the rest of the items with figma.

> Not sure about the features section in plan

Also not too sure whether this is needed

**Comment by Tbaut** [comment]
We can leave the feature section out for now.
