### ISSUE TITLE
"Go back" confusion when paying

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1897]
from https://github.com/ChainSafe/ui-monorepo/pull/1890#issuecomment-1024598483
![image](https://user-images.githubusercontent.com/33178835/151841522-a7884dd9-da18-4a1b-a15f-cb4eca0ba55d.png)

These 2 "go back" are confusing
We should remove the whole bottom bar, and only use the "Go back" and "Use this card".

**Comment by asnaith** [comment]
Nice, I was just about to create this 😆
