### ISSUE TITLE
Circular progress bar doesn't reflect the real progress

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1904]
It's somewhat a nit, but it annoyed me enough to log it :D

If you play with the Circular progress on Storybook, and set the progress to 40 (click 3 times on "add 10"), it'll look like 50%, e.g
![image](https://user-images.githubusercontent.com/33178835/151980564-023b59e9-7062-409b-bb46-e892aabf9fac.png)

This is 50% (clicking 4 times on add 10)
![image](https://user-images.githubusercontent.com/33178835/151982787-409e49a7-22ee-4689-a317-08ee5920f3fe.png)

I figured this is directly related to the width, here's the same 40%, and 50% with a 100px width - it's looking good:
![image](https://user-images.githubusercontent.com/33178835/151980766-64bb4299-3e6c-47da-9028-caca125ef59d.png)
![image](https://user-images.githubusercontent.com/33178835/151982889-bd922e12-e171-4dee-93e5-d3efbc1bcc83.png)

I tried to dig a bit, but couldn't figure out quickly enough.

Either one of you has an idea, or we can forget about it for now.

**Comment by FSM1** [comment]
ahhh I also noticed this the last time I was working with the circular progress bar. Will do a bit more digging
