### ISSUE TITLE
Improve toggle state so that it persists between modal transitions

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1905]
Currently, the toggle state for annual / monthly billing does not persist. 

If you back out back to the select plan modal, the next one you choose revert back to monthly. Similarly, if you choose annual billing, select a plan but then return to the modal from the select payment modal the toggle state reverts back to monthly. 

https://user-images.githubusercontent.com/3982665/152030733-f19f0b9b-6f93-4051-821f-1482687d17dd.mov

**Comment by Tbaut** [comment]
The first pattern, (set to annual, then go back), the toggle should be reset. The second pattern in video is where the toggle should still be set.
