### ISSUE TITLE
General feedback on the file preview

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1909]
@Tbaut commented on [Tue Mar 02 2021](https://github.com/ChainSafe/files-design/issues/91)

I have had this feeling since the beginning, I just realized what I thought was a bug, was actually on purpose.
The top menu stopping _almost_ in the middle of the screen looks weird to me, also having the options button here is not where I'd expect it to be (in a corner).
 
![image](https://user-images.githubusercontent.com/33178835/109665140-2908e580-7b6e-11eb-9a15-d5b7e75ed55c.png)

Another remark, I've felt lost a often times looking for a way to close this full screen modal, looking for a cross in the top right, but ended up realizing that the left arrow at the top left was achieving this function. I think this is not intuitive and we should have a cross, in the top right hand corner.

---

@Tbaut commented on [Fri Mar 05 2021](https://github.com/ChainSafe/files-design/issues/91#issuecomment-791421653)

Transfered to the design repo as discussed, so that we can have new mocks for it, since it's not a bug.

**Comment by Tbaut** [comment]
That's still actual and has totally been forgotten IMHO

**Comment by Tbaut** [comment]
@serenaho I think we have a design for this for ages. This is almost a year old, and could be tackled any time IMHO. What do you think?

**Comment by serenaho** [comment]
I created some updated options for file previewing in the [Figma here](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=1775%3A75007). You'll see that the designs vary by file format.

I noticed that the previous versions had the same menu options as on the regular UI (as you will see in Figma). The only thing that I need clarification on is whether or not we want to keep the menu items or reduce it down to only Download (in which case I would switch the icon to become a download icon).

**Comment by Tbaut** [comment]
This is looking awesome, thanks a lot. I think having more option can make a lot of sense, like delete, but as you point out in your design, it means we would need to have some modal on top of the preview, and also some pretty custom behaviors. This would be pretty tricky to implement nicely.

I'd say we should start small and just go with the design changes in this issue, and add more menu in the future if required.

**Comment by FSM1** [comment]
> I created some updated options for file previewing in the [Figma here](https://www.figma.com/file/wRMGqc11iQLVpDVmqXVXWK/ChainSafe-Files?node-id=1775%3A75007). You'll see that the designs vary by file format.
> 
> I noticed that the previous versions had the same menu options as on the regular UI (as you will see in Figma). The only thing that I need clarification on is whether or not we want to keep the menu items or reduce it down to only Download (in which case I would switch the icon to become a download icon).

Agreed with @Tbaut that for now we can limit it to just the download, and we can expand the options available in due course
