### ISSUE TITLE
Add some information regarding the crypto time lock

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1911]
We should add some information to tell our users that the cryto price will be locked for 60min

**Comment by serenaho** [comment]
Here is my suggested solution/copy. Let me know if it makes sense:

![Change Plan _ Review Plan Change.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/72ef15cb-5961-4dc6-b699-c04d9be4cf5b)

**Comment by Tbaut** [comment]
That's perfect, thank you so much
