### ISSUE TITLE
Add Final Sale/Non-Refundable warnings to Billing Flow

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1912]
On the downgrade modal
- for credit card we should tell that the users will get unused credit
- for crypto we should tell that there is no refund.

**Comment by serenaho** [comment]
Suggested copy for downgrading plans with CC & crypto:

![Switch plans with annual billing control (in app)](https://user-images.githubusercontent.com/91699405/152261337-4f007046-1ae8-4e02-8d56-b014bf37a600.png)

![SwitchPlans_Warning](https://user-images.githubusercontent.com/91699405/152261932-7de3bcfa-2032-44e8-bdcf-7075e410661f.png)

**Comment by serenaho** [comment]
Suggested copy for CC and Crypto payment billing flows:

![Change Plan _ CC Review Plan Change](https://user-images.githubusercontent.com/91699405/152261520-4d242660-8fab-4a18-911a-5f1caae48de4.png)

![Send Crypto to QR Code](https://user-images.githubusercontent.com/91699405/152261522-10bd021c-3e44-4622-bd82-8f494619b51c.png)

**Comment by Tbaut** [comment]
Looks good, thanks @serenaho !
