### ISSUE TITLE
Clicking enabled on Settings header area

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1913]
I noticed that I am currently able to click on the Settings header area and that it will take me back to the Profile and Display tab every time.

https://images.zenhubusercontent.com/285884697/2266d57b-0c3a-484b-8fee-96b4e90a077e/settings__button_.mov

Suggested solution: Make it not clickable

**Comment by Tbaut** [comment]
I'd say this is pretty helpful for mobile, to go back to the tab overview though. I happened to click on it once and was happy to see the behavior. Is that really that annoying on desktop?

**Comment by serenaho** [comment]
Hmm you bring up a really good point about navigation within Settings however it's inconsistent with the same headers in other pages like Home and Shared. I'm not sure this is the right fix but I'll give it some more thought and draft up other options! Thanks Thibaut

**Comment by Tbaut** [comment]
And just as an additional info, I did not know about the click on Setting before actually trying something out on mobile.
I was the one saying we didn't need a navigation for the settings on mobile because users on real devices can use the native navigation to go back. But I think I was wrong since even I didn't use it :D

**Comment by Tbaut** [comment]
Any thought on this @asnaith @tanmoyAtb @FSM1 ?

**Comment by FSM1** [comment]
I was also pleasantly surprised by the ability to navigate back by touching the header. I think relying on the user to use a hardware `back` button is very presumptuous, as this is not available on apple devices.

It's not exactly the most intuitive, but functionally serves it's purpose.

**Comment by Tbaut** [comment]
It can be a gesture, like newer Android navigation or iOS, in any case they can go back with the device "go back". The thing is that in a react app, many interaction don't actually involve any routing, and I guess we're used to it, so that we try to actually use any app's back button before resorting to the device one.

Maybe we should have a "go back" arrow at the top?

**Comment by asnaith** [comment]
> Any thought on this @asnaith @tanmoyAtb @FSM1 ?

I was under the impression it was intentional behaviour, just like tapping the Files logo in the header will take you to the home (Drive) page. I agree that the current state is a benefit to people on mobile

**Comment by serenaho** [comment]
I did some digging and it looks like a good solution is placing a "back" button at the top left (see below, replacing the menu icon while user is in Settings). I think this solution is effective because it creates an almost breadcrumb-like feedback for the user to navigate. 

Is this feasible / what are your thoughts @FSM1 @Tbaut @asnaith ?

https://user-images.githubusercontent.com/91699405/153273633-8d73afd0-df7e-4fa4-8cef-54176326ae70.mov

**Comment by asnaith** [comment]
It's a nice alternative to the clickable header and certainly more obvious to the user but also it seems like this functionality would only be relevant on the settings page as none of the other features are using tabs?

**Comment by serenaho** [comment]
Yes my thoughts were that it would be solely for the purpose of navigating within Settings, since it functions differently compared to the rest of the UI.

**Comment by Tbaut** [comment]
It would indeed not be straight forward to implement, since the header is totally independent from the rest and generally doesn't know what is below. I'm also worried that we break something relatively consistant on the whole app, just for the settings.

**Comment by Tbaut** [comment]
How about adding a left arrow to indicate that clicking on that title would bring you back to the settings, like that. we can add this only for mobile.
![image](https://user-images.githubusercontent.com/33178835/153483977-21693306-b963-43f3-b400-e10b6e84277f.png)

**Comment by FSM1** [comment]
> How about adding a left arrow to indicate that clicking on that title would bring you back to the settings, like that. we can add this only for mobile. ![image](https://user-images.githubusercontent.com/33178835/153483977-21693306-b963-43f3-b400-e10b6e84277f.png)

Yeah this seems like the cleanest option to me.

**Comment by serenaho** [comment]
After discussing with @Tbaut, we've decided not to fiddle with the existing nav, and go ahead with the above option by @FSM1. Additionally, we'll also reduce the size of the overall button so that it doesn't become a huge Settings button. 


<img width="535" alt="Screen Shot 2022-02-11 at 9 09 21 AM" src="https://user-images.githubusercontent.com/91699405/153636816-08ec3856-4dc0-4e5e-811a-8ba2eada4356.png">
