### ISSUE TITLE
Fix user sign-out button

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/files-ui#1920]
The button looks fine using a wallet address but touches the edge when credentials are different like so:

![image.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/817cfae2-0e15-4461-8ae9-88a0686fea0b)

![Screen Shot 2022-02-07 at 10.53.13 AM.png](https://images.zenhubusercontent.com/615b27919165edef4fb3f145/90307024-ad6b-4128-9564-85684cd0db19)

We should try and fix this with other credential considerations in mind such as Files IDs and usernames. Perhaps we could set a max width for the button and just add a “…” at the end of the credential when it gets too long.

**Comment by Tbaut** [comment]
Agreed, we should have elipsis for anything
