### ISSUE TITLE
"Confirm plan change" error message persists on modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1922]
**Description**
After invoking an error message on the "confirm plan change" modal, if you leave and return (even after selecting a new payment type) the original message will still be displayed. 

**Steps to Reproduce**
1. Go through the payment flow to upgrade a plan
2. Try to pay for a plan with a credit card that will fail
3. Observe the failure message
4. Click "go back"
5. Choose crypto as the payment type and return to the "confirm plan change" 

**Observed behavior**
Original error message relating to the failed credit card transaction is still displayed

**Expected behavior**
Error message should not be retained after navigating away from the modal and returning

**Video**

https://user-images.githubusercontent.com/3982665/152876853-610a907a-be99-4219-9f8d-f8f21c0e7a22.mov

**Desktop:**
 - Not specific to any browser / os combo.

**Comment by Tbaut** [comment]
I think this will be handled in https://github.com/ChainSafe/ui-monorepo/pull/1900 I'll check
