### ISSUE TITLE
Include full payment reminder on the "Pay with crypto" modal

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1926]
**Problem:**  Currently, if a user makes a partial crypto payment, we won’t act on it and it will stay in the crypto account. This will be handled by refund/credit flow in future but as of now this is the situation.

**V1 Solution:** 

- Add a reminder to the "Pay with crypto" modal informing the user that they must make a full payment when they are sending cyrpto

- Update the currency label underneath QR code to use `ETH` rather than `ethereum`

<img width="487" alt="Screen Shot 2022-02-08 at 10 07 04 AM" src="https://user-images.githubusercontent.com/3982665/153049359-fc58355e-1b8e-46e2-8b4a-2d44ddde7aad.png">

**Comment by Tbaut** [comment]
We should not add yet another warning (there's already one after https://github.com/ChainSafe/ui-monorepo/pull/1924) I'm for changing the copy eventually for the "Only send the exact amount of ETH to this address"

**Comment by asnaith** [comment]
@Tbaut Sounds good, I was unaware of the other ticket. Perhaps all we need to discuss in planning is a copy change on this modal. Will keep it open for now.

**Comment by Tbaut** [comment]
Absolutely, I change adapting the copy that is already there, on your screenshot, would make the most sense. Because the other warning I just added is about reimbursement rather than the payment itself.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1926?planning-poker) with ZenHub @tanmoyAtb @Tbaut
