### ISSUE TITLE
Use icon in sharing overview

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1928]
Now that we have nice icons, we should use them instead of the user icon I believe. I don't think we'd need design for this.
IMHO these should be updated
![image](https://user-images.githubusercontent.com/33178835/153236672-be650b73-2ddb-4686-b2a9-4d7c365659c2.png)

Only use identicon for the primary user, and have the `+n` in the same style as it is now

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1928?planning-poker) with ZenHub @tanmoyAtb @Tbaut
