### ISSUE TITLE
Remove owner from the shared with list

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1929]
When looking at the sharing overview, I had the impression that the owner would not be part of the shared user column. But it actually is, using its username, making it even more confusing. Here's an example, I'm the owner of this one, and the first person that's shared with is actually the same, myself:
![image](https://user-images.githubusercontent.com/33178835/153237567-af22e88b-abd4-4d6c-b656-afebd0ae9786.png)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1929?planning-poker) with ZenHub @tanmoyAtb @Tbaut
