### ISSUE TITLE
New shared folder modal design isn't aligned with the others

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1941]
Having the buttons be centered and the close button below the main button is unusual.

![image](https://user-images.githubusercontent.com/33178835/153849035-7f4b2ce7-14fb-4cc5-abf2-cbf7ec7b53a2.png)

**Comment by FSM1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1941?planning-poker) with ZenHub @Tbaut
