### ISSUE TITLE
Shared folder creation should allow link creation right away

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1943]
As discussed:
- Shared folder creation should first ask for the shared folder name, and nothing else
- upon creation we should show the manage permission modal, allowing to add users/ create links

**Comment by FSM1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1943?planning-poker) with ZenHub @Tbaut
