### ISSUE TITLE
Focus state on buttons in the preview in dark mode make the button invisible

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1964]
from https://github.com/ChainSafe/ui-monorepo/pull/1960#pullrequestreview-888584444

In dark mode, click on some buttons. When they are active, they aren't visible
![image](https://user-images.githubusercontent.com/33178835/155121322-30fe84d8-87ad-452d-bfce-1b1351053b4e.png)

https://user-images.githubusercontent.com/33178835/154969151-2a873d0c-9e61-4f15-a817-cdd5d2624ce0.mp4

Add more contrast for the colors in dark mode

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1964?planning-poker) with ZenHub @tanmoyAtb @Tbaut
