### ISSUE TITLE
One pager PDF files are not displayed correctly in Preview (mobile)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1966]
**Description**

Mobile only - The aspect ratio of a one page PDF file is too zoomed in when previewed on a mobile device. It doesn't seem to happen with PDF's containing multiple pages. 

It is not possible to adjust this manually which means there's no way a single page PDF can be viewed correctly. 

**To Reproduce**
1. Upload a single page PDF (I used the ChainSafe invoice PDF!)
2. Navigate to preview

**Expected behavior**
The PDF file view should scale to display everything on the page without zooming. 

**Video**

https://user-images.githubusercontent.com/3982665/155214776-865ef11d-317e-4c99-8d4b-2ada6eed1224.MP4

**Smartphone:**
 - OS: iOS
 - iPhone 12 Mini
 - Browser: Safari
 - Version: 15

- OS: Android
- Pixel 6 Pro
- Browser: Chrome
- version: 98

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1966?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by tanmoyAtb** [comment]
Hey, @FSM1 I think you had a couple of files to test this issue.

**Comment by asnaith** [comment]
@tanmoyAtb Our ChainSafe Invoice PDF can be used, it's one of the files that wasn't scaling correctly
