### ISSUE TITLE
Difficulty scanning QR code in dark theme (Android) 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1967]
This is not a bug per se but a consideration for perhaps a better approach on the below modal: 

<img width="488" alt="Screen Shot 2022-02-22 at 3 42 01 PM" src="https://user-images.githubusercontent.com/3982665/155238601-6e86286c-b29c-417d-ad44-ccd38f52b963.png">

On an iPhone 12 I have no difficulties scanning the QR code in both themes but on an Android device (Pixel 6 Pro) I cannot scan the QR code in dark mode. Scanning the code only works for me on Android in the light theme. 

I don't have a wider pool of devices to test this out on but as the Android phone I used is one of the latest I suspect it could be a problem for many more, especially lower-end devices. 

Update text colors for warning to ensure higher contrast

**Comment by Tbaut** [comment]
Ah, this is something I know, QR codes need some delimitation. We need to add a white border of a couple pixels around it, that'll do the trick
