### ISSUE TITLE
OS video controls displayed upon preview modal closure (iOS only)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1970]
**Description**
When you preview a video file on iOS within safari, if you close the preview modal without playing the video then the OS video control interface is left behind and also have to be closed before you can return to the main drive page. 

**Steps to Reproduce**
1. Log in to Files on Safari within iOS
2. Upload a movie
3. Preview movie
4. Close preview modal without playing the video

**Observed behavior**
After closing the video the OS video controls are left behind and have to be closed before you can return to the drive page.

**Expected behavior**
Closing the modal should take the user back to the main drive page

**Video**

https://user-images.githubusercontent.com/3982665/155373064-c1aedd74-0af8-47e5-8a43-00bf73bab0f5.mov

**Notes**

- This is specific to Safari on iOS. It doesn't happen on Firefox on iOS or on MacOS version of Safari, Android etc. 

- iOS is the only platform that doesn't auto-play the videos when they are previewed. If you play the video and then close the preview modal everything works so perhaps the fix for this is to ensure videos auto-play like they do on every other platform?

**Comment by tanmoyAtb** [comment]
Hey @asnaith , I could not really replicate the issue on my side.
I'm using safari on an iPhone. I tried closing the preview before starting play on a video, and during playing. 


https://user-images.githubusercontent.com/10713353/156220323-ab184c36-cf47-4632-8f35-fa28159855e0.mov

**Comment by asnaith** [comment]
@tanmoyAtb oh strange! I can still reproduce it, could you try with the same file I am using? [ChainSafe Files link](https://app.files.chainsafe.io/link-sharing/read/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibGlua19zaGFyaW5nIiwicGVybWlzc2lvbiI6InJlYWQiLCJpYXQiOjE2NDY4NzIzNjUsImJ1Y2tldF9pZCI6IjY2ZjFiZWM0LTEzM2ItNGVkZC1iNmNmLWI1YjQyYWMyMzU5NSIsIm5vbmNlX2lkIjoiNWUxZTMzYmItMTVlMi00ODY3LWI5MWItYTI1MmRiMmM3YjE3In0.Uw6qf7Dt_Uy2SZdXahKmp2uYp37wfZJmXqPh1y0UNe5btb0D3Lu7T2h14cZ80peViuCvW1jzhWkwAjKTfiEFFw#UGpFmoAqwU5QaFi%2BQnnd6%2FzjHBCRPfeYSKEnxrLAfBI%3D)

Also, I'm on iOS 15.3.1 - I know Safari had a lot of new changes in iOS 15 so perhaps it's version-specific too. 

I have reproduced it on another iPhone, a different model to my personal device but it was still on iOS 15.3.1

**Comment by tanmoyAtb** [comment]
> @tanmoyAtb oh strange! I can still reproduce it, could you try with the same file I am using? [ChainSafe Files link](https://app.files.chainsafe.io/link-sharing/edit/eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibGlua19zaGFyaW5nIiwicGVybWlzc2lvbiI6IndyaXRlIiwiaWF0IjoxNjQ2MTYxOTM1LCJidWNrZXRfaWQiOiIzZGVkYWExYS1mZDUzLTQxM2ItOTFlNC0zYWI2ZTkxMmJmMzkiLCJub25jZV9pZCI6ImRhNTUzMWZlLWM5N2UtNGMxNy1iY2YxLWMxN2RlYzY0N2QzOSJ9.84N64sr_dlGZ4IR5jzwXTuHmOAzO0ArQy3QSdrzado6wT_xLVwsE31H1bu-2JqtgKGptmJJ2SS-F4fdqk4-d9A#1K38venR8cQ0oyOBXANcY%2B7tQbBhkLiNWl90%2FHWoX5Y%3D)
> 
> Also, I'm on iOS 15.3.1 - I know Safari had a lot of new changes in iOS 15 so perhaps it's version-specific too.
> 
> I have reproduced it on another iPhone, a different model to my personal device but it was still on iOS 15.3.1

Looks like I had an older version, and it was working there. I'm upgrading to 15.3.1 now, will check it out.

**Comment by tanmoyAtb** [comment]
Hey @asnaith I tried to replicate this again, it still seems to be working with 15.3.1 on my device.

**Comment by asnaith** [comment]
> Hey @asnaith I tried to replicate this again, it still seems to be working with 15.3.1 on my device.

Yeah this bug is strange. I just checked again on 2 different iPhones, both on 15.3.1 and it's still happening on those for me 🤦‍♂️.

Due to the fact it only happens if you don't play the video before closing (and that most users will want to play when they go to the preview) and it's not affecting all iPhones / iOS versions then maybe we need to keep this in backlog until we have better reproduction steps? 

It's feeling like more of a quirk with the way Safari and its video controls are handling the video but it's strange that it's not happening 100%. Not sure if it's related to auto-play.
