### ISSUE TITLE
Text input background in Light Mode

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#1981]
**Describe the bug**
Text Input background color in Light mode is not right

**To Reproduce**
1. Go to the https://app.files.chainsafe.io
2. Observe the text input has a dark background in `light` mode

**Expected behavior**
The input should have a light background in light mode

**Screenshots**
![image](https://user-images.githubusercontent.com/12774278/155713567-2ee0550a-77c3-4511-816e-0ab965bc3da9.png)
![image](https://user-images.githubusercontent.com/12774278/155713618-05233b3d-f74e-4c84-ba53-9a9ff3faa813.png)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**

**Comment by asnaith** [comment]
This is strange, I've never seen this before and still can't reproduce it on prod. I wonder if it is OS / Browser specific.

**Comment by FSM1** [comment]
hmmm not seeing this happening in prod any more either (tested both Brave & Firefox) 🤷🏼
