### ISSUE TITLE
"Manage Shared Folder" modal does not display address / keys correctly

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1984]
**Description**
The layout of the "Manage Shared Folder" modal cannot properly accommodate an Ethereum address or share key, in the case of share key it makes the access rights dropdown inaccessible. 

**Steps to Reproduce**
1. Share a folder to ethereum address or share key

**Observed behavior**

<img width="518" alt="Screen Shot 2022-02-25 at 1 10 03 PM" src="https://user-images.githubusercontent.com/3982665/155807445-bf204c42-0ba1-4469-917b-551927a4e45b.png">

<img width="526" alt="Screen Shot 2022-02-25 at 1 06 20 PM" src="https://user-images.githubusercontent.com/3982665/155807455-d474afb3-60e8-463d-96e5-9f6c25c27fb8.png">

**Expected behavior**
I guess we should truncate or resize the address / key string so that it fits correctly

**Console Error**

**Screenshots**

**Desktop:**
 - OS: macOS
 - Browser: Chrome (not browser specific)
 - Version : 98.0.4758.109

**Comment by Tbaut** [comment]
From what I could see, the eth address was fine, the shared key may have been the issue
edit: ah when we add them they aren't trimmed you're right
