### ISSUE TITLE
Add notifications to Storage

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1992]
With https://github.com/ChainSafe/ui-monorepo/pull/1983 adding the billing, all the notifications part was left out, and commented.
This issue should take care of the design for the notification bell, as well as the automatic creation of notifications when the account has open invoices.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/1992?planning-poker) with ZenHub @tanmoyAtb @Tbaut
