### ISSUE TITLE
"Allow lookup" checkbox should be its own menu

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#1994]
When looking at this screenshot, the checkbox to allow lookup seems to be only related to the username, although it's a general lookup agreement.

I'd suggest to use a toggle, and make it big, and separate from the others (maybe even first wdyt?)

![image](https://user-images.githubusercontent.com/33178835/156183681-71b7ce46-8a31-4756-a0f0-0ab3e73f680a.png)

**Comment by asnaith** [comment]
Totally makes sense to me, will be a nice improvement 👍
