### ISSUE TITLE
"Manage Shared Folder" access right option obscured when lookup results are open

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#1998]
**Description**
The access rights dropdown becomes partially obscured when the lookup results are open

**Steps to Reproduce**
1. Create a new shared folder
2. Enter the name of a user and leave lookup results open
3. Click on the access permission dropdown

**Expected behavior**
The options should never be obscured by another element.

Perhaps we should close the lookup results if the access rights dropdown is clicked? 

**Video**

https://user-images.githubusercontent.com/3982665/156274761-38e5e2b1-2a5c-41c8-833e-0f0524c55650.mov

**Desktop:**
 - OS: macOS
 Browser: Chrome (not browser specific)
 - Version : 98.0.4758.109

**Comment by FSM1** [comment]
Either z-index for the dropdown, or close the lookup results when clicking away on the dropdown
