### ISSUE TITLE
Header elements partially obscured on default presentation (Safari / iOS 15 only)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2011]
**Description**
After logging in, the default view which is presented has the feature header pushed up and partially obscured behind the top bar component. 

This issue is only affecting iPhone devices with small screens (iPhone SE and iPhone Mini) and iOS 15. Safari on iOS 15 is the only mobile browser on iOS that has an address bar at the bottom by default, it seems to be this which is causing the issue. It doesn't happen when the browser address bar is at the top or using a bigger mobile device. 

**Steps to Reproduce**
1. Login on Safari on iOS 15 
2. Look at default presentation of components 

**Expected behavior**
The starting position of the feature header (and list/grid icons etc) should be in view and should only go behind the top bar component when scrolling. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/3982665/157506565-1d3a9c20-c845-4628-a8b5-009f2cfd63cc.jpeg" width="400">

**Mobile:**
 - Version : Safari / iOS 15.3

**Comment by tanmoyAtb** [comment]
Hey @asnaith, For some reason I couldn't reproduce this problem as well. I tried this on an iPhone 8 (the small screen one), on 15.4, the UI looks fine, both production and staging.

**Comment by asnaith** [comment]
Hey @tanmoyAtb, yeah it seems to be resolved now. I can no longer reproduce it on the original device! We can close this issue
