### ISSUE TITLE
[Storage] Add support for restricted accounts

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2020]
Implement restricted account UI elements (banner and disable uploads)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2020?planning-poker) with ZenHub @tanmoyAtb @Tbaut
