### ISSUE TITLE
Allow search/filtering by pin name or cid

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2024]
The search should be:
- calling the `list` from the api, with partial match, when what is types isn't a cid.
- calling the `list` by cid if what is typed looks like a cid (with can use the `isCid` helper)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2024?planning-poker) with ZenHub @tanmoyAtb @Tbaut
