### ISSUE TITLE
Show an informative message when selecting files that will reach the storage limit

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2030]
As we know the upload size before the "upload" button is clicked, we should warn users about it, and redirect them to the form to get to the early adopter users, able to subscribe to paid plans.

**Comment by FSM1** [comment]
How should the DnD case be handled?

**Comment by Tbaut** [comment]
Good point, I guess, for the sake of helping, we should actually not allow to drop a file, or a set of files which will go over the plan's allowed storage.

**Comment by FSM1** [comment]
Another case we should consider, which I don't see an easy way to handle right now, is the case of uploads to a shared folder by a `writer` where the user uploading does not have visibility of the amount of space available to the owner's account.

**Comment by Tbaut** [comment]
Good point, maybe a call to the api would be required in that case.
