### ISSUE TITLE
Click outside should save a renaming action

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2050]
Based on me shadowing a Files user, and checking the behavior of a normal OS (windows or linux but I bet mac is the same).
When you click out after renaming a file, it actually saves it. On files it cancels the renaming action.

**Comment by asnaith** [comment]
> Based on me shadowing a Files user, and checking the behavior of a normal OS (windows or linux but I bet mac is the same).

Yeah it is the same on macOS 👍
