### ISSUE TITLE
With a long list of files on desktop the bulk actions should be sticky to the top of the screen

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2052]
When you have a lot of files and select some, it's not immediately obvious that you have access to bulk actions on the top.
We should make sure that the bulk actions are visible and sticky at the top of the screen

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2052?planning-poker) with ZenHub @tanmoyAtb @Tbaut
