### ISSUE TITLE
Storage Bucket Browser layout broken

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/files-ui#2055]
**Describe the bug**
File browser layout is broken

**To Reproduce**
1. Log in to storage
2. Navigate inside a bucket with some contents
3. Observe broken layout

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12774278/160646988-00e5497b-d0b1-400b-b8e4-3ad132bce21c.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: N/A

**Comment by Tbaut** [comment]
Woops that must be me in https://github.com/ChainSafe/ui-monorepo/pull/2036 with the grid size. I'll check it out

**Comment by Tbaut** [comment]
Hmm I can't replicate on FF and brave on dev
![image](https://user-images.githubusercontent.com/33178835/160667690-9837ffd9-c96f-4c23-8541-b1c0146e1977.png)
