### ISSUE TITLE
[Storage] Incorrect colour on slide-out menu elements 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2082]
**Describe the bug**
On Storage the space used has text and a log-out button that are the wrong colour: 

![IMG_3671](https://user-images.githubusercontent.com/3982665/162517855-d61f871a-404a-4249-9581-55d3f26b435f.jpg)

**Comment by Tbaut** [comment]
Just a note that Storage was kept minimal so far with no mobile support officially (like the column etc don't look good)
