### ISSUE TITLE
[Storage] Broken layout on API key page (mobile)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2083]
**Describe the bug**
The layout is broken when viewing the api key page on a mobile device. 

**To Reproduce**
1. Go to the API key page
2. Create a key if you don't already have one
3. Observe the layout 

**Video**

https://user-images.githubusercontent.com/3982665/162519549-052e64cb-8779-4e4f-bab9-c48c2059f3a4.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Mini / Google Pixel Pro 6 
 - OS: iOS 15.4.1 / Android 12
 - Browser: Stock Safari / Mobile Chrome

**Comment by FSM1** [comment]
Closing due to impractical implementation on mobile
