### ISSUE TITLE
[Storage] Element positioning issue on slide-out navigation (Android) 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2087]
**Description**
When you navigate back and forth between the buckets page and cids page the positioning of the navigation elements will break. 

**I could only reproduce this on Android, in either Chrome or the Metamask app browser** 

**Steps to Reproduce**
1. Log into storage on Android
2. Navigate back and forth between bucket page and cid page

**Observed behavior**

https://user-images.githubusercontent.com/3982665/162813244-b4350995-e5b2-4a55-b3b0-e886624c8066.mp4

**Expected behavior**
Menu elements should not change position. 

**Desktop:**
 - OS: Android 12
 Browser: Chrome / Android Metamask app
 - Version : 100.0.4896.79

**Comment by FSM1** [comment]
Timebox this investigation.
