### ISSUE TITLE
[Storage] No error message when trying to use folder name already in use

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2088]
**Description**
There is no error message displayed to the user when they attempt to create a new folder that has the same name as one already in use

**Steps to Reproduce**
1. Log in to storage
2. Create a folder
3. Attempt to create another folder with the same name as before

**Observed behavior**
The user can click the "create" button and the modal disappears, no folder is created because one already exists, no message given to the user. 

**Expected behavior**
The user should remain on the modal and see a "Folder name is already in use" red text error label (like Files). 

**Video**

https://user-images.githubusercontent.com/3982665/162814694-a0e505da-1d1d-41f8-a1ea-ece6a2701cae.mov

**Desktop:**
 - Not OS / browser specific

**Comment by FSM1** [comment]
Ensure that the error is caught on both IPFS and Chainsafe filesystem buckets, and an error message is displayed in the modal dialog (same behavior as Files)

**Comment by tanmoyAtb** [comment]
The current API behaviour is different for IPFS and CS file systems. Thee IPFS bucket, `mkdir` API does not respond with conflict response now.

**Comment by tanmoyAtb** [comment]
The API is now updated to handle duplicate folder names in IPFS and CS file systems. We can close this issue. I've checked and implementation is working perfect.
