### ISSUE TITLE
[Files] The directory name display overflows with a directory nested deep enough.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2093]
**Describe the bug**
With really deep directories, the display of the name will overflow in the UI. Additionally, the slash symbols acting as dividers for the directory names will disappear.

**To Reproduce**
1. Keep creating directory names until the display overflows.

**Expected behavior**
If the directory is very deeply nested, the display should be appropriately collapsed or should continue growing *downwards* once the full width of the display is reached.

**Screenshots**
![Directory Overflow](https://user-images.githubusercontent.com/56321034/163563872-c70d283f-0541-473d-99f3-04927c4617d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2093?planning-poker) with ZenHub @tanmoyAtb @Tbaut
