### ISSUE TITLE
When holding the `SHIFT` key, the user should be able to select all files within a range.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2094]
**Is your feature request related to a problem? Please describe.**
When selecting files in any kind of file explorer, I have grown accustomed to being able to use the `CTRL` key to select particular files in no specific order, and the `SHIFT` key to select files within a certain frame.  However, when holding the `SHIFT` key, nothing happens.

**Describe the solution you'd like**
When holding the `SHIFT` key while selecting files, the selection of files should be extended from the farthermost file to the selected files.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2094?planning-poker) with ZenHub @tanmoyAtb @Tbaut
