### ISSUE TITLE
Right-clicking on the page should serve the user with a custom menu, rather than browser page settings.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2095]
**Is your feature request related to a problem? Please describe.**
Computer users are especially accustomed to working with menus shown after right-clicking.  In a file explorer, the user -- after right-clicking -- is likely to expect a menu to show up with a concise selection of functions which are usually also available elsewhere in the application.  However, currently, right-clicking causes the standard browser page manipulation menu to show up.

**Describe the solution you'd like**
When right-clicking on the page, a menu themed similarly to the rest of the application should be shown to the user, allowing them to select from a concise menu of options.

**Comment by FSM1** [comment]
Menu options should be dependent on the state of the file browser
- Right click on blank area of file browser
  - Create a folder
  - Upload files
- Right click on a single item
  - All that item's 3 dot menu options
- Right click when multiple items are selected
  - Bulk action menu options should be displayed

**Comment by FSM1** [comment]
https://mui.com/material-ui/react-menu/#context-menu
