### ISSUE TITLE
The user should be able to choose between binary (multiples of 2; KiB, MiB, GiB, ...) and convenience (multiples of 10; KB, MB, GB, ...) formats for viewing their files.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2096]
**Is your feature request related to a problem? Please describe.**
Currently, the user is shown their file sizes in the binary format, where the difference between size denominations are 1024x.  However, a large number of users -- especially users of Windows, who do not have their file sizes shown in this format -- work with and are accustomed to convenience sizes, where the difference is 1000x.

**Describe the solution you'd like**
The user should be able to choose how their file sizes should be displayed.

**Comment by Tbaut** [comment]
I'm not totally sold on this idea. How do other file storage like GDrive or Dropbox work? The idea is to prevent having feature creep, too many settings prevent users from having too many options. Maybe we could change strategy based on the os?

**Comment by vxern** [comment]
I don't know about Dropbox, but Google Drive seems to show the sizes only in the convenience format (GB).

Changing the file size method based on the operating system seems like a good compromise to limiting the number of options the user has within the application.  However, I'd like to point out that, for similar convenience reasons, even though the language of the app is determined by the language of the browser accessing it, the user is still able to change the language.  Therefore, I believe it would be right to provide the user with a similar choice for their file sizes.

**Comment by FSM1** [comment]
@vxern I did some digging and while Google Drive as well as windows explorer uses the `MB` label, they actually display the size in `MiB` - i.e. Base 2

See the below:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/12774278/167850446-a5c21e18-a159-4142-876d-738f502b9298.png">

40152 Bytes = 39.2 KiB = 40.2 KB

Displayed by Google as `39 KB`, which should actually be `39 KiB`
![image](https://user-images.githubusercontent.com/12774278/167850684-42e9c391-2cc8-4a0d-8334-579caf554c5a.png)
