### ISSUE TITLE
[Files] Uploading a large number of files in separate directories causes a very large number of unnecessary notifications to pop up.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2097]
**Describe the bug**
When trying to upload various directories and their contained files at the same time, a notification will pop up for every directory being uploaded, taking up the whole height of the screen.

**To Reproduce**
1. Upload a large number of files in separate directories.

**Expected behavior**
A single notification pertaining to the single transfer of files to Files should be shown to the user, rather than a separate notification for each directory.

**Screenshots**
![NotificationsUploading](https://user-images.githubusercontent.com/56321034/163566088-3fa0896a-258a-414f-96b4-ff48a1c58d86.png)
![NotificationsUploaded](https://user-images.githubusercontent.com/56321034/163566091-649e7d64-1577-4094-b988-9e724e374d0c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2097?planning-poker) with ZenHub @tanmoyAtb @Tbaut

**Comment by FSM1** [comment]
Implement a `Upload Manager` layer that will handle the notification for a single user action (uploading multiple folders) and figure out the total file size to keep track of progress of the overall upload.

TBC: How are we going to handle an individual upload that fails as part of a batch?
