### ISSUE TITLE
[Files] Significant number of directories and files missing after upload.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2098]
**Describe the bug**
While attempting to upload a directory with a large number of sub-directories, which in turn have sub-sub-directories, etc., the files fail to upload, with a sizeable chunk of them missing.

**To Reproduce**
1. Create a directory `Test`.
2. In the `Test` directory, create 3 sub-directories named `A`, `B`, and `C`.
3. To the `Test` directory, add 3 text files called `a.txt`, `b.txt`, and `c.txt`.
4. To the `A`, `B` and `C` directories, add 3 text files `a.txt`, `b.txt` and `c.txt`.
5. Drag the `Test` directory over to Files.

**Expected behavior**
The file structure of the `Test` directory should look as follows:
```markdown
- Test/
  - A/
    - a.txt
    - b.txt
    - c.txt
  - B/
    - a.txt
    - b.txt
    - c.txt
  - C/
    - a.txt
    - b.txt
    - c.txt
  - a.txt
  - b.txt
  - c.txt    
```

**Observed behavior**
The file structure of the `Test` directory after uploading looks as follows:
```markdown
- Test/
  - A/
    - a.txt
    - b.txt
    - c.txt
  - B/
    - a.txt
    - b.txt
    - c.txt
``` 

**Screenshots**
![Animation](https://user-images.githubusercontent.com/56321034/163571591-869c96c3-b26f-4d9c-9bf8-e2b22556d850.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Comment by Tbaut** [comment]
I could reproduce once I had many sub dir files

```
/Test
├── a
├── A
│   ├── a
│   ├── b
│   └── c
├── b
├── B
│   ├── a
│   ├── b
│   └── c
├── c
└── C1
    ├── a
    ├── b
    ├── c
    └── C2
        ├── a
        ├── b
        ├── c
        └── C3
            ├── a
            ├── b
            ├── c
            └── C4
                ├── a
                ├── b
                └── c
```

The C3 only contained C4, not the a, b and c files. Checking it out.

**Comment by Tbaut** [comment]
After checking with the back end, each request is sent as expected, but there's a lock happening there. We need to batch those uploads.
