### ISSUE TITLE
[Files] Directories refuse to be uploaded.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2100]
**Describe the bug**
Directories refuse to be uploaded to Files.

**Expected behavior**
The directory along with its contents should be uploaded as expected.

**Console error**
No console error message.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/56321034/163693093-cb5d5ab7-3c02-42f2-9d8b-f6e545b068ff.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Comment by Tbaut** [comment]
it looks like a browser issue. The window doesn't show that there's something dragged to it. Could you check whether this is only happening to 1 specific directory?

**Comment by vxern** [comment]
Whoops.  I just checked, and I didn't realise at first that directories weren't being uploaded because they were empty.
