### ISSUE TITLE
Text selection using mouse does not work while renaming files.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2102]
**Describe the bug**
While attempting to rename a file, I am not able to use the mouse to select the text.

**To Reproduce**
1. Upload any file or directory.
2. While renaming the directory, attempt to select text using the mouse.

**Expected behavior**
Text should be selected, instead of the app detecting a mouse drag action.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/56321034/163730604-62a43ed9-30f0-457e-8931-cc9d4b7ea624.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 99.0.1

**Comment by Tbaut** [comment]
Thanks for reporting this Dorian, we've fixed it recently in https://github.com/ChainSafe/ui-monorepo/pull/2067 and it'll be part of the next release, live most prob in the next days.

**Comment by vxern** [comment]
Ah, okay, great.  Closing.
