### ISSUE TITLE
Add breadcrumb to Bin browser

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2103]
**Is your feature request related to a problem? Please describe.**
While navigating through directories in the Bin area, I expected to be able to return to the parent directory, but found that the path was not being shown for trashed directories.

**Describe the solution you'd like**
The path should be shown as it is in the Home and Shared areas.

**Comment by FSM1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2103?planning-poker) with ZenHub @Tbaut
