### ISSUE TITLE
Empty directories are not uploaded.

### ISSUE THREAD

**Issue by vxern** [ChainSafe/files-ui#2104]
**Describe the bug**
The app ignores empty directories, and will not upload them.

**To Reproduce**
1. Try to upload an empty directory.

**Comment by Tbaut** [comment]
I don't think this is a bug, it's the way we built the app to work afair. @tanmoyAtb do you know if we had a technical reason not to create folders or was is an arbitrary choice?

 In any case I remember being surprise by the behavior myself, so I think it's a good idea to implement it.

**Comment by tanmoyAtb** [comment]
> I don't think this is a bug, it's the way we built the app to work afair. @tanmoyAtb do you know if we had a technical reason not to create folders or was is an arbitrary choice?
> 
> In any case I remember being surprise by the behavior myself, so I think it's a good idea to implement it.

AFAIR, there is a limitation on the API side in saving paths to empty folders, as the backend mainly deals with paths to files. We'll need more input from their side on this one.

**Comment by FSM1** [comment]
We would need to get a list of all the paths where empty folders need to be created and call `mkdir` with the right params.

The main issue here is how we get the folder names from the various dropzone / upload modal components to generate the list of `mkdir` calls that need to be made.
