### ISSUE TITLE
[Files] Drag and drop a folder on file browser is uploading OS files

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2112]
**Describe the bug**
When you drag and drop a folder containing files on the file browser it uploads the folders and files correctly but it also uploads OS files, eg. DS_Store. 

This only happens if you drag and drop on file browser, **it doesn't happen if you drag and drop on the modal**

**To Reproduce**
1. Login to Files
2. Drag and drop a folder with files to 'My Files'
3. Double click in the folder uploaded
4. See files imported

**Expected behavior**
Only regular files should be uploaded, system files should not be included

**Video**

https://user-images.githubusercontent.com/104365141/165584729-3ec36951-77c7-4040-9e70-4e91562a56be.mov

**Desktop (please complete the following information):**
Mac

**Additional context**
This only happens if you drag and drop on the file browser, **it doesn't happen if you drag and drop on the modal**

**Comment by FSM1** [comment]
Investigate how the modal determines whether a file is hidden and attempt to reimplement this in the file browser DnD handler.
