### ISSUE TITLE
Port dismissible toast behaviour to Storage UI

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2118]
We did some work in the Files UI to make toasts dismissible. It would be good to port this across to Storage UI too.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2118?planning-poker) with ZenHub @tanmoyAtb @Tbaut
