### ISSUE TITLE
Not able to select multiple files with cmd + click on the checkbox in Firefox

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2123]
**Describe the bug**

**To Reproduce**
1. Login to Files or Storage
2. Open a Bucket if you are in Storage
3. Click inside the checkbox of any of the files in the table using "cmd + click" (Mac) or "ctrl + click" (Windows)
4. Nothing happens

**Expected behavior**
File is selected (if was unselected previously) or unselected (if was selected previously)

**Video**

https://user-images.githubusercontent.com/104365141/167641286-ed51d616-5f7e-4958-b88d-ba9c597940b7.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox
 - Version 100.0

**Additional context**
This is happening in both **Files** and **Storage**

**Comment by Tbaut** [comment]
Closed by #2109
