### ISSUE TITLE
Update configuration parameters for UI test jobs

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2133]
We are currently using a docker container with an old version of chrome in our UI test execution (91.0.4472.114). 

We should update to the latest cypress docker container (see: https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md)

Also, our slack notification bot is not sending out notifications upon failure (thanks for noticing @juans-chainsafe !)

**Tasks**

- Change the container param in the below files to the reflect a more up to date container

`.github/workflows/test-files-on-demand.yml`
`.github/workflows/test-files.yml`
`.github/workflows/test-storage-on-demand.yml`
`.github/workflows/test-storage.yml`

- Update the slack notification in  the below files so that the notification task runs even if tests fail

`.github/workflows/test-files-on-demand.yml`
`.github/workflows/test-storage-on-demand.yml`

**Acceptance Criteria**

- All .yml files are updated
- All jobs continue to execute the UI tests as intended after the update

**Comment by juans-chainsafe** [comment]
Because we are editing the yml files to complete this task, we need to fix the issue that the slack notification is not being pushed when the tests fail, to fix this we need to add `if: always()` inside the slack step

**Comment by asnaith** [comment]
> Because we are editing the yml files to complete this task, we need to fix the issue that the slack notification is not being pushed when the tests fail, to fix this we need to add `if: always()` inside the slack step

Makes sense to make both changes at the same time 👍. I changed the name of the issue to better reflect what we are doing.
