### ISSUE TITLE
Notify users when they reach 75% of their storage quota 

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/files-ui#2146]
**Task**

In order to provide awareness of our upgrade feature 

**For all users that have reached 75% of their storage quota** 

- Present a notification in the notification manager informing the user that they have reached 75% of their storage quota. 

**For users who are on the early access list AND have reached 75% of their storage quota** 

- Present a notification in the notification manager informing the user that they have reached 75% of their storage quota and the notification should have an upgrade link which when clicked takes the user to the Billing tab within Settings

- Change the "Need more storage" button to "Upgrade" which when clicked also takes the user to the Billing tab within Settings

**Comment by Tbaut** [comment]
I'd show the notification to every user, not only the ones that are on the whitelist. Just the text and link should differ and point toward the form to request access to this feature.

**Comment by asnaith** [comment]
> I'd show the notification to every user, not only the ones that are on the whitelist. Just the text and link should differ and point toward the form to request access to this feature.

@Tbaut sounds good. I've updated the original description
