### ISSUE TITLE
Add right click menu to Shared folder and Bucket overview

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2153]
The buckets overview in Storage and the Shared folder overview in Files do not have a right click menu yet.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2153?planning-poker) with ZenHub @tanmoyAtb @Tbaut
