### ISSUE TITLE
[Storage] Add a modal confirmation for bucket deletion

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2170]
Right now when deleting a bucket, it's done right away. This is obviously a little dangerous since it's a very destructive action, we should double check with the user that it's not a mis-click.

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2170?planning-poker) with ZenHub @tanmoyAtb @Tbaut
