### ISSUE TITLE
[Storage] Add sort in Buckets table

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2174]
**Is your feature request related to a problem? Please describe.**
Should be good to have the sorting in that table, because we have it in all other tables, so in this way we maintain a standard.

**Describe the solution you'd like**
Add the ability to sort by:
- Name
- File System
- Size

**Additional context**
![Screen Shot 2022-06-08 at 09.35.15.png](https://images.zenhubusercontent.com/62699f50d2fb4f7e13688714/35b5c09e-b293-48ea-aef6-ec17693e5a17)

**Comment by FSM1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2174?planning-poker) with ZenHub @tanmoyAtb @Tbaut
