### ISSUE TITLE
[Storage] Add ability to rename a Bucket 

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/files-ui#2183]
**Description**
I want to be able to rename an existing Bucket in Storage for type '**Chainsafe**' and '**IPFS**'

**Additional context**
<img width="922" alt="Screen Shot 2022-06-10 at 10 33 44" src="https://user-images.githubusercontent.com/104365141/173076975-104911e4-ce47-4120-8d32-8c59a1dc3c37.png">

**Comment by ColinSchwarz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Files-5eb5ea92d698464ed9543f62/issues/ChainSafe/ui-monorepo/2183?planning-poker) with ZenHub @tanmoyAtb @Tbaut
