### ISSUE TITLE
Couldnt loggin  Chainsafe file through MetaMask wallet on local net.

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/files-ui#2216]
### Discussed in https://github.com/ChainSafe/ui-monorepo/discussions/2215

<div type='discussions-op-text'>

<sup>Originally posted by **achnir97** July  7, 2022</sup>
I am not being able to connect the Chainsafe Files to Metamask wallet while running on local-net. If any body had the same issue and had solved the problem, I would highly appreciate for the solution.</div>

**Comment by Tbaut** [comment]
@achnir97 can you walk us through the steps you follow to have the issue, any screenshot is welcome.
1. Do I understand correctly that you are building the application from the sources?
2. Can you share your env file?
3. Can you tell us what is exactly failing, when do you see an error, and eventually show the errors from the console?

Thanks

**Comment by achnir97** [comment]
> @achnir97 can you walk us through the steps you follow to have the issue, any screenshot is welcome.
> 
> 1. Do I understand correctly that you are building the application from the sources?
> 2. Can you share your env file?
> 3. Can you tell us what is exactly failing, when do you see an error, and eventually show the errors from the console?
> 
> Thanks
 
Yeah i am building the application from the source . 
Error in the console is as follows: 
<img width="605" alt="Screenshot 2022-07-07 at 10 46 41 PM" src="https://user-images.githubusercontent.com/63242285/177789228-c4febde9-6f42-4ce4-ba7a-5ea7139d59be.png">

Thank you.

**Comment by achnir97** [comment]
> @achnir97 can you walk us through the steps you follow to have the issue, any screenshot is welcome.
> 
> 1. Do I understand correctly that you are building the application from the sources?
> 2. Can you share your env file?
> 3. Can you tell us what is exactly failing, when do you see an error, and eventually show the errors from the console?
> 
> Thanks
Env file has been attached as follows:
<img width="779" alt="Screenshot 2022-07-07 at 10 50 21 PM" src="https://user-images.githubusercontent.com/63242285/177790044-52f5501d-b9ed-476a-935f-a9525e6bef2c.png">

**Comment by FSM1** [comment]
> > @achnir97 can you walk us through the steps you follow to have the issue, any screenshot is welcome.
> > 
> > 1. Do I understand correctly that you are building the application from the sources?
> > 2. Can you share your env file?
> > 3. Can you tell us what is exactly failing, when do you see an error, and eventually show the errors from the console?
> > 
> > Thanks
> > Env file has been attached as follows:

First things first, create a copy of the `.env.example` file, and rename it to `.env`

The correct variables should get picked up when you start up the local server

**Comment by achnir97** [comment]
> 

Thank you so much. It solved my problem.
