### ISSUE TITLE
Connecting with Filecoin network..

### ISSUE THREAD

**Issue by achnir97** [ChainSafe/files-ui#2217]
I am new to ChainSafe Storage and ChainSafe Files. 
How do i upload my file in Filecoin network  through ChainSafe Files?
I am still not understanding how ChainSafe Files Leverages users to connect with filecoin Network. 
I would be greateful for the help.

**Comment by Tbaut** [comment]
I believe we have answered your questions on our Telegram group. Closing this for now.
