### ISSUE TITLE
Files UI - Sharing v1

### ISSUE THREAD

**Issue by tanmoyAtb** [ChainSafe/files-ui#383]
![image](https://user-images.githubusercontent.com/12774278/117160963-db089c00-adc1-11eb-99e8-2668e698fcc6.png)

The process for share creation is as follows:
1. User chooses a file or folder that they would like to share
2. (Fetch folder size) The File size is displayed, and confirmation is requested that they would like to start the transfer (if file size is large)
3. A symmetric key is generated by the owner, and encrypted with their public key
4. A request is made to the API to create a shared bucket, and the encrypted symmetric key is passed to the bucket
5. Transfer of the existing data can happen.
4. While the transfer is happening, the owner can look up and add users to the share. Progress bar for upload should be displayed.
5. When the user is done adding collaborators to the share, they can push a button to close the modal.
6. If the transfer is not yet done, a Toast notification with a progress bar should be displayed.
7. Call API method to remove the original content from the file system and create a reference item to the shared file system

Details to be finalized once https://github.com/ChainSafe/files-design/issues/96 has been completed

![image](https://user-images.githubusercontent.com/12774278/104855942-4e23fa80-5918-11eb-9a93-d93f53c81c44.png)
![image](https://user-images.githubusercontent.com/12774278/104855950-5bd98000-5918-11eb-93b0-32ee05a00848.png)

**Comment by Tbaut** [comment]
This Epic issue can be found https://github.com/ChainSafe/files-design/issues/83 closing this one.
